root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build/dev/go"
  entrypoint = "/tmp/bin/rigelledger"
  delay = 100
  exclude_dir = ["web", "tmp"]
  include_ext = ["go", "sql"]
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500

[misc]
  clean_on_exit = true
