/*
 * Vendors all-set-tw's connectors at one pinned commit, and bundles each
 * into vendor/all-set-tw/<connector>.js for Node.
 *
 *   bun scripts/vendor.ts <commit>   copy the files at <commit>, then bundle
 *   bun scripts/vendor.ts            bundle the copies already here again
 *   bun scripts/vendor.ts --check    fail if a bundle is not what its copies give (CI)
 *
 * Upstream is TypeScript for Cloudflare Workers: extensionless imports,
 * parameter properties, and @cloudflare/puppeteer. Node's type stripping
 * runs none of that, so Bun bundles each connector once, here, with
 * @cloudflare/puppeteer left as an import of our stand-in
 * (src/browser/cloudflare.ts), and npm packages (zod, jpeg-js, ...) left
 * as imports. The copies are never edited: to move to a
 * newer upstream, run this with the new commit and review the diff.
 */
import { $ } from 'bun';
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, relative } from 'node:path';

const REPO = 'https://github.com/TedLin1993/all-set-tw.git';
const ROOT = join(import.meta.dir, '..');
const VENDOR = join(ROOT, 'vendor', 'all-set-tw');
const SHIM = join(ROOT, 'src', 'browser', 'cloudflare.ts');

// Upstream files, by path in the all-set-tw repo.
const FILES = [
  'LICENSE',
  'apps/worker/src/sources/types.ts',
  'apps/worker/src/sources/browser.ts',
  'apps/worker/src/sources/sync-window.ts',
  'apps/worker/src/sources/credit-card-status.ts',
  'apps/worker/src/sources/cathaybk/protocol.ts',
  'apps/worker/src/sources/cathaybk/connector.ts',
  'apps/worker/src/sources/sinopac/protocol.ts',
  'apps/worker/src/sources/sinopac/deposit-protocol.ts',
  'apps/worker/src/sources/sinopac/connector.ts',
  'apps/worker/src/sources/tdcc/epassbook-client.ts',
  'apps/worker/src/sources/tdcc/protocol.ts',
];

// One bundle per connector: what our wrapper imports from it.
const BUNDLES: Record<string, string> = {
  cathaybk: 'apps/worker/src/sources/cathaybk/connector.ts',
  sinopac: 'apps/worker/src/sources/sinopac/connector.ts',
  tdcc: 'apps/worker/src/sources/tdcc/protocol.ts',
};

async function fetchUpstream(commit: string) {
  const tmp = await mkdtemp(join(tmpdir(), 'all-set-tw-'));
  try {
    await $`git clone --quiet --filter=blob:none --no-checkout ${REPO} ${tmp}`;
    await $`git -C ${tmp} checkout --quiet ${commit}`;
    const full = (await $`git -C ${tmp} rev-parse HEAD`.text()).trim();
    const date = (await $`git -C ${tmp} show -s --format=%cs HEAD`.text()).trim();
    await rm(join(VENDOR, 'apps'), { recursive: true, force: true });
    for (const f of FILES) {
      await mkdir(dirname(join(VENDOR, f)), { recursive: true });
      await cp(join(tmp, f), join(VENDOR, f));
    }
    await writeFile(join(VENDOR, 'UPSTREAM'), `${REPO}\n${full}\n${date}\n`);
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}

async function bundle(id: string, entry: string): Promise<string> {
  const out = await Bun.build({
    entrypoints: [join(VENDOR, entry)],
    target: 'node',
    format: 'esm',
    minify: false,
    plugins: [{
      name: 'cloudflare-puppeteer-stand-in',
      setup(b) {
        b.onResolve({ filter: /^@cloudflare\/puppeteer$/ }, () => ({
          path: relative(VENDOR, SHIM).replaceAll('\\', '/').replace(/^(?!\.)/, './'),
          external: true,
        }));
        // npm packages stay imports, at the versions in package.json (upstream's
        // lockfile): the bundle holds upstream's code only.
        b.onResolve({ filter: /^[a-z@][^:]*$/ }, (a) => (a.importer ? { path: a.path, external: true } : undefined));
      },
    }],
  });
  if (!out.success) throw new AggregateError(out.logs, `bundling ${id} failed`);
  const [upstream, commit] = (await readFile(join(VENDOR, 'UPSTREAM'), 'utf8')).split('\n');
  return `// all-set-tw ${entry} at ${commit} (${upstream}), MIT: see LICENSE.\n`
    + '// Generated by scripts/vendor.ts from the copies under apps/; do not edit.\n'
    + (await out.outputs[0].text());
}

process.chdir(ROOT); // Bun names each module in the bundle by its path from here
const args = process.argv.slice(2);
const check = args.includes('--check');
const commit = args.find((a) => !a.startsWith('--'));
if (commit) await fetchUpstream(commit);

let stale = 0;
for (const [id, entry] of Object.entries(BUNDLES)) {
  const path = join(VENDOR, `${id}.js`);
  const js = await bundle(id, entry);
  if (check) {
    const have = await readFile(path, 'utf8').catch(() => '');
    if (have !== js) {
      console.error(`${relative(ROOT, path)} is not what its vendored source bundles to; run bun scripts/vendor.ts`);
      stale++;
    }
  } else {
    await writeFile(path, js);
    console.error(`wrote ${relative(ROOT, path)}`);
  }
}
process.exit(stale ? 1 : 0);
