// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_requests.sql

package db

import (
	"context"
	"net/netip"
	"time"
)

const createAccessRequest = `-- name: CreateAccessRequest :one
INSERT INTO access_requests (username, email, message, ip)
VALUES ($1, $2, $3, $4::inet)
RETURNING id, username, email, message, coalesce(host(ip), '')::TEXT AS ip, status, decided_by, decided_at, created_at
`

type CreateAccessRequestParams struct {
	Username string
	Email    string
	Message  string
	Ip       *netip.Addr
}

type CreateAccessRequestRow struct {
	ID        int64
	Username  string
	Email     string
	Message   string
	Ip        string
	Status    string
	DecidedBy *int64
	DecidedAt *time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) (CreateAccessRequestRow, error) {
	row := q.db.QueryRow(ctx, createAccessRequest,
		arg.Username,
		arg.Email,
		arg.Message,
		arg.Ip,
	)
	var i CreateAccessRequestRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Message,
		&i.Ip,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const decideAccessRequest = `-- name: DecideAccessRequest :execrows
UPDATE access_requests SET status = $1, decided_by = $2, decided_at = now()
WHERE id = $3 AND status = 'pending'
`

type DecideAccessRequestParams struct {
	Status    string
	DecidedBy *int64
	ID        int64
}

func (q *Queries) DecideAccessRequest(ctx context.Context, arg DecideAccessRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideAccessRequest, arg.Status, arg.DecidedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccessRequest = `-- name: GetAccessRequest :one
SELECT id, username, email, message, coalesce(host(ip), '')::TEXT AS ip, status, decided_by, decided_at, created_at
FROM access_requests WHERE id = $1
`

type GetAccessRequestRow struct {
	ID        int64
	Username  string
	Email     string
	Message   string
	Ip        string
	Status    string
	DecidedBy *int64
	DecidedAt *time.Time
	CreatedAt time.Time
}

func (q *Queries) GetAccessRequest(ctx context.Context, id int64) (GetAccessRequestRow, error) {
	row := q.db.QueryRow(ctx, getAccessRequest, id)
	var i GetAccessRequestRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Message,
		&i.Ip,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAccessRequests = `-- name: ListAccessRequests :many
SELECT id, username, email, message, coalesce(host(ip), '')::TEXT AS ip, status, decided_by, decided_at, created_at
FROM access_requests
WHERE $1::TEXT IS NULL OR status = $1::TEXT
ORDER BY created_at DESC
LIMIT 200
`

type ListAccessRequestsRow struct {
	ID        int64
	Username  string
	Email     string
	Message   string
	Ip        string
	Status    string
	DecidedBy *int64
	DecidedAt *time.Time
	CreatedAt time.Time
}

func (q *Queries) ListAccessRequests(ctx context.Context, status *string) ([]ListAccessRequestsRow, error) {
	rows, err := q.db.Query(ctx, listAccessRequests, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessRequestsRow{}
	for rows.Next() {
		var i ListAccessRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Message,
			&i.Ip,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminEmails = `-- name: ListAdminEmails :many
SELECT email FROM users WHERE is_admin AND is_active AND email <> ''
`

func (q *Queries) ListAdminEmails(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAdminEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingAccessRequestExists = `-- name: PendingAccessRequestExists :one
SELECT EXISTS (
    SELECT 1 FROM access_requests
    WHERE status = 'pending' AND (lower(email) = lower($1) OR username = $2)
)
`

type PendingAccessRequestExistsParams struct {
	Email    string
	Username string
}

func (q *Queries) PendingAccessRequestExists(ctx context.Context, arg PendingAccessRequestExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, pendingAccessRequestExists, arg.Email, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
