// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const accountCostBasis = `-- name: AccountCostBasis :one
SELECT coalesce(sum(p.amount), 0)::numeric      AS quantity,
       coalesce(sum(p.base_amount), 0)::numeric AS cost
FROM postings p
JOIN transactions t ON t.id = p.transaction_id
WHERE p.account_id = $1
  AND t.date <= $2
  AND t.id <> $3
`

type AccountCostBasisParams struct {
	AccountID            int64
	AsOf                 time.Time
	ExcludeTransactionID int64
}

type AccountCostBasisRow struct {
	Quantity decimal.Decimal
	Cost     decimal.Decimal
}

// What an account holds and what it cost, up to a date: the input to average
// cost when miles, points or shares leave it. Excludes one transaction, so
// editing a redemption does not count the redemption itself.
func (q *Queries) AccountCostBasis(ctx context.Context, arg AccountCostBasisParams) (AccountCostBasisRow, error) {
	row := q.db.QueryRow(ctx, accountCostBasis, arg.AccountID, arg.AsOf, arg.ExcludeTransactionID)
	var i AccountCostBasisRow
	err := row.Scan(&i.Quantity, &i.Cost)
	return i, err
}

const accountHasChildren = `-- name: AccountHasChildren :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE parent_id = $1)
`

func (q *Queries) AccountHasChildren(ctx context.Context, parentID *int64) (bool, error) {
	row := q.db.QueryRow(ctx, accountHasChildren, parentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accountHasPostings = `-- name: AccountHasPostings :one
SELECT EXISTS (SELECT 1 FROM postings WHERE account_id = $1)
`

func (q *Queries) AccountHasPostings(ctx context.Context, accountID int64) (bool, error) {
	row := q.db.QueryRow(ctx, accountHasPostings, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accountSums = `-- name: AccountSums :many
SELECT p.account_id,
       p.commodity,
       coalesce(sum(p.amount), 0)::numeric      AS amount,
       coalesce(sum(p.base_amount), 0)::numeric AS base_amount
FROM postings p
JOIN transactions t ON t.id = p.transaction_id
WHERE t.book_id = $1 AND t.date <= $2
GROUP BY p.account_id, p.commodity
`

type AccountSumsParams struct {
	BookID int64
	AsOf   time.Time
}

type AccountSumsRow struct {
	AccountID  int64
	Commodity  string
	Amount     decimal.Decimal
	BaseAmount decimal.Decimal
}

// Balances as of a date, per account and commodity. Income and expense
// accounts can hold several currencies, hence the commodity grouping.
func (q *Queries) AccountSums(ctx context.Context, arg AccountSumsParams) ([]AccountSumsRow, error) {
	rows, err := q.db.Query(ctx, accountSums, arg.BookID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountSumsRow{}
	for rows.Next() {
		var i AccountSumsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Commodity,
			&i.Amount,
			&i.BaseAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (book_id, parent_id, class, name, template_key, code, commodity,
                      is_current, is_cash, cf_class, is_placeholder)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11)
RETURNING id, book_id, parent_id, class, name, template_key, code, commodity, is_current, is_cash, cf_class, is_placeholder, archived_at, created_at, updated_at
`

type CreateAccountParams struct {
	BookID        int64
	ParentID      *int64
	Class         AccountClass
	Name          *string
	TemplateKey   *string
	Code          *string
	Commodity     *string
	IsCurrent     bool
	IsCash        bool
	CfClass       CfClass
	IsPlaceholder bool
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.BookID,
		arg.ParentID,
		arg.Class,
		arg.Name,
		arg.TemplateKey,
		arg.Code,
		arg.Commodity,
		arg.IsCurrent,
		arg.IsCash,
		arg.CfClass,
		arg.IsPlaceholder,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.ParentID,
		&i.Class,
		&i.Name,
		&i.TemplateKey,
		&i.Code,
		&i.Commodity,
		&i.IsCurrent,
		&i.IsCash,
		&i.CfClass,
		&i.IsPlaceholder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE book_id = $1 AND id = $2
`

type DeleteAccountParams struct {
	BookID int64
	ID     int64
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, arg.BookID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, book_id, parent_id, class, name, template_key, code, commodity, is_current, is_cash, cf_class, is_placeholder, archived_at, created_at, updated_at FROM accounts WHERE book_id = $1 AND id = $2
`

type GetAccountParams struct {
	BookID int64
	ID     int64
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.BookID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.ParentID,
		&i.Class,
		&i.Name,
		&i.TemplateKey,
		&i.Code,
		&i.Commodity,
		&i.IsCurrent,
		&i.IsCash,
		&i.CfClass,
		&i.IsPlaceholder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByTemplateKey = `-- name: GetAccountByTemplateKey :one
SELECT id, book_id, parent_id, class, name, template_key, code, commodity, is_current, is_cash, cf_class, is_placeholder, archived_at, created_at, updated_at FROM accounts WHERE book_id = $1 AND template_key = $2
`

type GetAccountByTemplateKeyParams struct {
	BookID      int64
	TemplateKey *string
}

func (q *Queries) GetAccountByTemplateKey(ctx context.Context, arg GetAccountByTemplateKeyParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByTemplateKey, arg.BookID, arg.TemplateKey)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.ParentID,
		&i.Class,
		&i.Name,
		&i.TemplateKey,
		&i.Code,
		&i.Commodity,
		&i.IsCurrent,
		&i.IsCash,
		&i.CfClass,
		&i.IsPlaceholder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, book_id, parent_id, class, name, template_key, code, commodity, is_current, is_cash, cf_class, is_placeholder, archived_at, created_at, updated_at FROM accounts WHERE book_id = $1 ORDER BY class, coalesce(code, ''), id
`

func (q *Queries) ListAccounts(ctx context.Context, bookID int64) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.ParentID,
			&i.Class,
			&i.Name,
			&i.TemplateKey,
			&i.Code,
			&i.Commodity,
			&i.IsCurrent,
			&i.IsCash,
			&i.CfClass,
			&i.IsPlaceholder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountArchived = `-- name: SetAccountArchived :one
UPDATE accounts SET archived_at = CASE WHEN $1::boolean THEN now() END
WHERE book_id = $2 AND id = $3
RETURNING id, book_id, parent_id, class, name, template_key, code, commodity, is_current, is_cash, cf_class, is_placeholder, archived_at, created_at, updated_at
`

type SetAccountArchivedParams struct {
	Archived bool
	BookID   int64
	ID       int64
}

func (q *Queries) SetAccountArchived(ctx context.Context, arg SetAccountArchivedParams) (Account, error) {
	row := q.db.QueryRow(ctx, setAccountArchived, arg.Archived, arg.BookID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.ParentID,
		&i.Class,
		&i.Name,
		&i.TemplateKey,
		&i.Code,
		&i.Commodity,
		&i.IsCurrent,
		&i.IsCash,
		&i.CfClass,
		&i.IsPlaceholder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts SET
    parent_id      = $1,
    name           = $2,
    code           = $3,
    is_current     = $4,
    is_cash        = $5,
    cf_class       = $6,
    is_placeholder = $7
WHERE book_id = $8 AND id = $9
RETURNING id, book_id, parent_id, class, name, template_key, code, commodity, is_current, is_cash, cf_class, is_placeholder, archived_at, created_at, updated_at
`

type UpdateAccountParams struct {
	ParentID      *int64
	Name          *string
	Code          *string
	IsCurrent     bool
	IsCash        bool
	CfClass       CfClass
	IsPlaceholder bool
	BookID        int64
	ID            int64
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ParentID,
		arg.Name,
		arg.Code,
		arg.IsCurrent,
		arg.IsCash,
		arg.CfClass,
		arg.IsPlaceholder,
		arg.BookID,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.ParentID,
		&i.Class,
		&i.Name,
		&i.TemplateKey,
		&i.Code,
		&i.Commodity,
		&i.IsCurrent,
		&i.IsCash,
		&i.CfClass,
		&i.IsPlaceholder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
