// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"
	"time"
)

const findAttachment = `-- name: FindAttachment :one
SELECT id FROM attachments WHERE book_id = $1 AND sha256 = $2
`

type FindAttachmentParams struct {
	BookID int64
	Sha256 []byte
}

func (q *Queries) FindAttachment(ctx context.Context, arg FindAttachmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, findAttachment, arg.BookID, arg.Sha256)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAttachmentFile = `-- name: GetAttachmentFile :one
SELECT id, filename, mime, size, bytes FROM attachments WHERE book_id = $1 AND id = $2
`

type GetAttachmentFileParams struct {
	BookID int64
	ID     int64
}

type GetAttachmentFileRow struct {
	ID       int64
	Filename string
	Mime     string
	Size     int32
	Bytes    []byte
}

func (q *Queries) GetAttachmentFile(ctx context.Context, arg GetAttachmentFileParams) (GetAttachmentFileRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentFile, arg.BookID, arg.ID)
	var i GetAttachmentFileRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Mime,
		&i.Size,
		&i.Bytes,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO attachments (book_id, sha256, filename, mime, size, bytes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (book_id, sha256) DO NOTHING
RETURNING id
`

type InsertAttachmentParams struct {
	BookID    int64
	Sha256    []byte
	Filename  string
	Mime      string
	Size      int32
	Bytes     []byte
	CreatedBy *int64
}

// Nothing when the book already holds this content: the caller reads its id.
func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.BookID,
		arg.Sha256,
		arg.Filename,
		arg.Mime,
		arg.Size,
		arg.Bytes,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const linkAttachment = `-- name: LinkAttachment :exec
INSERT INTO transaction_attachments (book_id, transaction_id, attachment_id, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (transaction_id, attachment_id) DO NOTHING
`

type LinkAttachmentParams struct {
	BookID        int64
	TransactionID int64
	AttachmentID  int64
	CreatedBy     *int64
}

func (q *Queries) LinkAttachment(ctx context.Context, arg LinkAttachmentParams) error {
	_, err := q.db.Exec(ctx, linkAttachment,
		arg.BookID,
		arg.TransactionID,
		arg.AttachmentID,
		arg.CreatedBy,
	)
	return err
}

const listTransactionAttachments = `-- name: ListTransactionAttachments :many
SELECT l.transaction_id, a.id, a.filename, a.mime, a.size, l.created_at
FROM transaction_attachments l JOIN attachments a ON a.id = l.attachment_id
WHERE l.transaction_id = ANY($1::BIGINT[])
ORDER BY l.id
`

type ListTransactionAttachmentsRow struct {
	TransactionID int64
	ID            int64
	Filename      string
	Mime          string
	Size          int32
	CreatedAt     time.Time
}

// What the transactions carry, without the bytes.
func (q *Queries) ListTransactionAttachments(ctx context.Context, transactionIds []int64) ([]ListTransactionAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionAttachments, transactionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionAttachmentsRow{}
	for rows.Next() {
		var i ListTransactionAttachmentsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.ID,
			&i.Filename,
			&i.Mime,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRowAttachment = `-- name: SetRowAttachment :exec
UPDATE import_rows SET attachment_id = $1 WHERE book_id = $2 AND id = $3
`

type SetRowAttachmentParams struct {
	AttachmentID *int64
	BookID       int64
	ID           int64
}

// A staged row's evidence, set once the row is known to be new.
func (q *Queries) SetRowAttachment(ctx context.Context, arg SetRowAttachmentParams) error {
	_, err := q.db.Exec(ctx, setRowAttachment, arg.AttachmentID, arg.BookID, arg.ID)
	return err
}

const unlinkAttachment = `-- name: UnlinkAttachment :execrows
DELETE FROM transaction_attachments
WHERE book_id = $1 AND transaction_id = $2 AND attachment_id = $3
`

type UnlinkAttachmentParams struct {
	BookID        int64
	TransactionID int64
	AttachmentID  int64
}

// The file itself goes with its last link (trigger drop_orphan_attachment).
func (q *Queries) UnlinkAttachment(ctx context.Context, arg UnlinkAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkAttachment, arg.BookID, arg.TransactionID, arg.AttachmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
