// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_events.sql

package db

import (
	"context"
	"net/netip"
	"time"
)

const countFailures = `-- name: CountFailures :one
SELECT
    count(*) FILTER (WHERE username = $1 AND ip = $2::inet) AS user_ip,
    count(*) FILTER (WHERE ip = $2::inet)                         AS ip,
    count(*) FILTER (WHERE username = $1 AND $1::TEXT <> '')   AS username,
    coalesce(min(created_at), now())::TIMESTAMPTZ                            AS oldest
FROM auth_events
WHERE failure
  AND created_at > now() - make_interval(secs => $3::BIGINT)
  AND (username = $1 OR ip = $2::inet)
`

type CountFailuresParams struct {
	Username      string
	Ip            *netip.Addr
	WindowSeconds int64
}

type CountFailuresRow struct {
	UserIp   int64
	Ip       int64
	Username int64
	Oldest   time.Time
}

// Failures inside the window for the three throttle keys, and when the
// oldest of each counted failure leaves the window.
func (q *Queries) CountFailures(ctx context.Context, arg CountFailuresParams) (CountFailuresRow, error) {
	row := q.db.QueryRow(ctx, countFailures, arg.Username, arg.Ip, arg.WindowSeconds)
	var i CountFailuresRow
	err := row.Scan(
		&i.UserIp,
		&i.Ip,
		&i.Username,
		&i.Oldest,
	)
	return i, err
}

const deleteOldAuthEvents = `-- name: DeleteOldAuthEvents :execrows
DELETE FROM auth_events WHERE created_at < now() - INTERVAL '180 days'
`

func (q *Queries) DeleteOldAuthEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldAuthEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuthEvents = `-- name: ListAuthEvents :many
SELECT id, username, user_id, coalesce(host(ip), '')::TEXT AS ip, user_agent, event, failure, detail, created_at
FROM auth_events
ORDER BY created_at DESC
LIMIT $1
`

type ListAuthEventsRow struct {
	ID        int64
	Username  string
	UserID    *int64
	Ip        string
	UserAgent string
	Event     string
	Failure   bool
	Detail    []byte
	CreatedAt time.Time
}

func (q *Queries) ListAuthEvents(ctx context.Context, lim int32) ([]ListAuthEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuthEvents, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthEventsRow{}
	for rows.Next() {
		var i ListAuthEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UserID,
			&i.Ip,
			&i.UserAgent,
			&i.Event,
			&i.Failure,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAuthEvents = `-- name: ListUserAuthEvents :many
SELECT id, username, user_id, coalesce(host(ip), '')::TEXT AS ip, user_agent, event, failure, detail, created_at
FROM auth_events
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListUserAuthEventsParams struct {
	UserID *int64
	Lim    int32
}

type ListUserAuthEventsRow struct {
	ID        int64
	Username  string
	UserID    *int64
	Ip        string
	UserAgent string
	Event     string
	Failure   bool
	Detail    []byte
	CreatedAt time.Time
}

func (q *Queries) ListUserAuthEvents(ctx context.Context, arg ListUserAuthEventsParams) ([]ListUserAuthEventsRow, error) {
	rows, err := q.db.Query(ctx, listUserAuthEvents, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAuthEventsRow{}
	for rows.Next() {
		var i ListUserAuthEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.UserID,
			&i.Ip,
			&i.UserAgent,
			&i.Event,
			&i.Failure,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuthEvent = `-- name: RecordAuthEvent :exec
INSERT INTO auth_events (username, user_id, ip, user_agent, event, failure, detail)
VALUES ($1, $2, $3::inet, $4, $5, $6, $7)
`

type RecordAuthEventParams struct {
	Username  string
	UserID    *int64
	Ip        *netip.Addr
	UserAgent string
	Event     string
	Failure   bool
	Detail    []byte
}

func (q *Queries) RecordAuthEvent(ctx context.Context, arg RecordAuthEventParams) error {
	_, err := q.db.Exec(ctx, recordAuthEvent,
		arg.Username,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
		arg.Event,
		arg.Failure,
		arg.Detail,
	)
	return err
}
