// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package db

import (
	"context"
	"time"
)

const addMember = `-- name: AddMember :exec
INSERT INTO book_members (book_id, user_id, role) VALUES ($1, $2, $3)
`

type AddMemberParams struct {
	BookID int64
	UserID int64
	Role   MemberRole
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.BookID, arg.UserID, arg.Role)
	return err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM book_members WHERE book_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, bookID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, bookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (name, base_currency, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, base_currency, lock_date, interest_dividend_cf_class, created_by, created_at, updated_at
`

type CreateBookParams struct {
	Name         string
	BaseCurrency string
	CreatedBy    *int64
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook, arg.Name, arg.BaseCurrency, arg.CreatedBy)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.LockDate,
		&i.InterestDividendCfClass,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBook = `-- name: GetBook :one
SELECT id, name, base_currency, lock_date, interest_dividend_cf_class, created_by, created_at, updated_at FROM books WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.LockDate,
		&i.InterestDividendCfClass,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM book_members WHERE book_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	BookID int64
	UserID int64
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (MemberRole, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.BookID, arg.UserID)
	var role MemberRole
	err := row.Scan(&role)
	return role, err
}

const listBooksForUser = `-- name: ListBooksForUser :many
SELECT b.id, b.name, b.base_currency, b.lock_date, b.interest_dividend_cf_class, b.created_by, b.created_at, b.updated_at, m.role
FROM books b
JOIN book_members m ON m.book_id = b.id
WHERE m.user_id = $1
ORDER BY b.name, b.id
`

type ListBooksForUserRow struct {
	Book Book
	Role MemberRole
}

func (q *Queries) ListBooksForUser(ctx context.Context, userID int64) ([]ListBooksForUserRow, error) {
	rows, err := q.db.Query(ctx, listBooksForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBooksForUserRow{}
	for rows.Next() {
		var i ListBooksForUserRow
		if err := rows.Scan(
			&i.Book.ID,
			&i.Book.Name,
			&i.Book.BaseCurrency,
			&i.Book.LockDate,
			&i.Book.InterestDividendCfClass,
			&i.Book.CreatedBy,
			&i.Book.CreatedAt,
			&i.Book.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT u.id AS user_id, u.username, u.display_name, m.role, m.created_at
FROM book_members m
JOIN users u ON u.id = m.user_id
WHERE m.book_id = $1
ORDER BY m.created_at, u.username
`

type ListMembersRow struct {
	UserID      int64
	Username    string
	DisplayName string
	Role        MemberRole
	CreatedAt   time.Time
}

func (q *Queries) ListMembers(ctx context.Context, bookID int64) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM book_members WHERE book_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	BookID int64
	UserID int64
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.BookID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books SET
    name                       = $1,
    lock_date                  = $2,
    interest_dividend_cf_class = $3
WHERE id = $4
RETURNING id, name, base_currency, lock_date, interest_dividend_cf_class, created_by, created_at, updated_at
`

type UpdateBookParams struct {
	Name                    string
	LockDate                *time.Time
	InterestDividendCfClass CfClass
	ID                      int64
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.Name,
		arg.LockDate,
		arg.InterestDividendCfClass,
		arg.ID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCurrency,
		&i.LockDate,
		&i.InterestDividendCfClass,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberRole = `-- name: UpdateMemberRole :execrows
UPDATE book_members SET role = $3 WHERE book_id = $1 AND user_id = $2
`

type UpdateMemberRoleParams struct {
	BookID int64
	UserID int64
	Role   MemberRole
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMemberRole, arg.BookID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
