// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commodities.sql

package db

import (
	"context"
)

const getCommodity = `-- name: GetCommodity :one
SELECT code, kind, name, decimals, quote_currency, exchange_mic FROM commodities WHERE code = $1
`

func (q *Queries) GetCommodity(ctx context.Context, code string) (Commodity, error) {
	row := q.db.QueryRow(ctx, getCommodity, code)
	var i Commodity
	err := row.Scan(
		&i.Code,
		&i.Kind,
		&i.Name,
		&i.Decimals,
		&i.QuoteCurrency,
		&i.ExchangeMic,
	)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT code, kind, name, decimals, quote_currency, exchange_mic FROM commodities WHERE kind = 'currency' ORDER BY code
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]Commodity, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Commodity{}
	for rows.Next() {
		var i Commodity
		if err := rows.Scan(
			&i.Code,
			&i.Kind,
			&i.Name,
			&i.Decimals,
			&i.QuoteCurrency,
			&i.ExchangeMic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
