// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package db

import (
	"context"
	"time"
)

const activeRunnerKey = `-- name: ActiveRunnerKey :one
SELECT id, public_key, created_at, retired_at FROM runner_keys WHERE retired_at IS NULL ORDER BY id DESC LIMIT 1
`

// What browsers seal to: the newest key the runner holds.
func (q *Queries) ActiveRunnerKey(ctx context.Context) (RunnerKey, error) {
	row := q.db.QueryRow(ctx, activeRunnerKey)
	var i RunnerKey
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const answerChallenge = `-- name: AnswerChallenge :execrows
UPDATE connection_challenges ch SET answer_sealed = $1, answered_at = now()
FROM connections c
WHERE ch.id = $2 AND c.id = ch.connection_id AND c.id = $3 AND c.user_id = $4
  AND ch.answered_at IS NULL AND ch.expires_at > now()
`

type AnswerChallengeParams struct {
	AnswerSealed []byte
	ID           int64
	ConnectionID int64
	UserID       int64
}

func (q *Queries) AnswerChallenge(ctx context.Context, arg AnswerChallengeParams) (int64, error) {
	result, err := q.db.Exec(ctx, answerChallenge,
		arg.AnswerSealed,
		arg.ID,
		arg.ConnectionID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimJobs = `-- name: ClaimJobs :many
UPDATE connections c SET claimed_at = now()
WHERE c.id IN (
    SELECT x.id FROM connections x JOIN runner_keys k ON k.id = x.key_id AND k.retired_at IS NULL
    WHERE x.enabled
      AND (x.claimed_at IS NULL OR x.claimed_at < now() - interval '30 minutes')
      AND (x.last_run_at IS NULL
           OR x.last_run_at < now() - make_interval(hours => x.interval_hours::INT)
           OR x.run_requested_at > x.last_run_at)
    ORDER BY x.last_run_at NULLS FIRST, x.id
    LIMIT $1
    FOR UPDATE OF x SKIP LOCKED
)
RETURNING c.id, c.user_id, c.book_id, c.connector, c.sealed, c.key_id
`

type ClaimJobsRow struct {
	ID        int64
	UserID    int64
	BookID    int64
	Connector string
	Sealed    []byte
	KeyID     int64
}

// Due connections, handed to one runner at a time: the claim lapses after 30
// minutes, so a runner that died mid-run does not strand its jobs.
func (q *Queries) ClaimJobs(ctx context.Context, lim int32) ([]ClaimJobsRow, error) {
	rows, err := q.db.Query(ctx, claimJobs, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimJobsRow{}
	for rows.Next() {
		var i ClaimJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Connector,
			&i.Sealed,
			&i.KeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createConnection = `-- name: CreateConnection :one

INSERT INTO connections (user_id, book_id, connector, label, sealed, key_id, interval_hours)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateConnectionParams struct {
	UserID        int64
	BookID        int64
	Connector     string
	Label         string
	Sealed        []byte
	KeyID         int64
	IntervalHours int16
}

// ---------------------------------------------------------------------------
// User side
// ---------------------------------------------------------------------------
func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.UserID,
		arg.BookID,
		arg.Connector,
		arg.Label,
		arg.Sealed,
		arg.KeyID,
		arg.IntervalHours,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createConnectionChallenge = `-- name: CreateConnectionChallenge :one
INSERT INTO connection_challenges (connection_id, kind, prompt, image, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, connection_id, kind, prompt, expires_at, created_at
`

type CreateConnectionChallengeParams struct {
	ConnectionID int64
	Kind         string
	Prompt       string
	Image        []byte
	ExpiresAt    time.Time
}

type CreateConnectionChallengeRow struct {
	ID           int64
	ConnectionID int64
	Kind         string
	Prompt       string
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

func (q *Queries) CreateConnectionChallenge(ctx context.Context, arg CreateConnectionChallengeParams) (CreateConnectionChallengeRow, error) {
	row := q.db.QueryRow(ctx, createConnectionChallenge,
		arg.ConnectionID,
		arg.Kind,
		arg.Prompt,
		arg.Image,
		arg.ExpiresAt,
	)
	var i CreateConnectionChallengeRow
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Kind,
		&i.Prompt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :execrows
DELETE FROM connections WHERE id = $1 AND user_id = $2
`

type DeleteConnectionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRunnerSession = `-- name: DeleteRunnerSession :execrows
DELETE FROM sessions WHERE id = $1 AND kind = 'runner'
`

func (q *Queries) DeleteRunnerSession(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRunnerSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishRun = `-- name: FinishRun :execrows
UPDATE connections SET status = $1, last_error = $2, last_run_at = now(), claimed_at = NULL
WHERE id = $3 AND claimed_at IS NOT NULL
`

type FinishRunParams struct {
	Status    string
	LastError string
	ID        int64
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRun, arg.Status, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClaimedConnection = `-- name: GetClaimedConnection :one
SELECT id, user_id, book_id, connector, label, sealed, key_id, enabled, interval_hours, status, last_error, last_run_at, run_requested_at, claimed_at, created_at, updated_at FROM connections WHERE id = $1 AND claimed_at IS NOT NULL
`

func (q *Queries) GetClaimedConnection(ctx context.Context, id int64) (Connection, error) {
	row := q.db.QueryRow(ctx, getClaimedConnection, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Connector,
		&i.Label,
		&i.Sealed,
		&i.KeyID,
		&i.Enabled,
		&i.IntervalHours,
		&i.Status,
		&i.LastError,
		&i.LastRunAt,
		&i.RunRequestedAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserConnection = `-- name: GetUserConnection :one
SELECT id, user_id, book_id, connector, label, enabled, interval_hours, status
FROM connections WHERE id = $1 AND user_id = $2
`

type GetUserConnectionParams struct {
	ID     int64
	UserID int64
}

type GetUserConnectionRow struct {
	ID            int64
	UserID        int64
	BookID        int64
	Connector     string
	Label         string
	Enabled       bool
	IntervalHours int16
	Status        string
}

func (q *Queries) GetUserConnection(ctx context.Context, arg GetUserConnectionParams) (GetUserConnectionRow, error) {
	row := q.db.QueryRow(ctx, getUserConnection, arg.ID, arg.UserID)
	var i GetUserConnectionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Connector,
		&i.Label,
		&i.Enabled,
		&i.IntervalHours,
		&i.Status,
	)
	return i, err
}

const listConnectors = `-- name: ListConnectors :many
SELECT id, name, country, fields, updated_at FROM runner_connectors ORDER BY country, name
`

func (q *Queries) ListConnectors(ctx context.Context) ([]RunnerConnector, error) {
	rows, err := q.db.Query(ctx, listConnectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunnerConnector{}
	for rows.Next() {
		var i RunnerConnector
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Country,
			&i.Fields,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnerKeys = `-- name: ListRunnerKeys :many
SELECT id, public_key, created_at, retired_at FROM runner_keys ORDER BY id DESC
`

func (q *Queries) ListRunnerKeys(ctx context.Context) ([]RunnerKey, error) {
	rows, err := q.db.Query(ctx, listRunnerKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunnerKey{}
	for rows.Next() {
		var i RunnerKey
		if err := rows.Scan(
			&i.ID,
			&i.PublicKey,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnerSessions = `-- name: ListRunnerSessions :many

SELECT s.id, s.label, s.created_at, s.last_used_at, s.expires_at, u.username
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.kind = 'runner' AND s.expires_at > now()
ORDER BY s.created_at
`

type ListRunnerSessionsRow struct {
	ID         int64
	Label      string
	CreatedAt  time.Time
	LastUsedAt time.Time
	ExpiresAt  time.Time
	Username   string
}

// ---------------------------------------------------------------------------
// Administration
// ---------------------------------------------------------------------------
func (q *Queries) ListRunnerSessions(ctx context.Context) ([]ListRunnerSessionsRow, error) {
	rows, err := q.db.Query(ctx, listRunnerSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunnerSessionsRow{}
	for rows.Next() {
		var i ListRunnerSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConnections = `-- name: ListUserConnections :many
SELECT c.id, c.book_id, b.name AS book_name, c.connector, c.label, c.enabled, c.interval_hours,
       c.status, c.last_error, c.last_run_at, c.run_requested_at, c.created_at,
       (k.retired_at IS NOT NULL)::BOOLEAN AS key_retired,
       -- challenge_id 0: nothing is waiting on this person
       coalesce(ch.id, 0)::BIGINT AS challenge_id, coalesce(ch.kind, '')::TEXT AS challenge_kind,
       coalesce(ch.prompt, '')::TEXT AS challenge_prompt, ch.image AS challenge_image,
       coalesce(ch.expires_at, c.created_at)::TIMESTAMPTZ AS challenge_expires_at
FROM connections c
JOIN books b ON b.id = c.book_id
JOIN runner_keys k ON k.id = c.key_id
LEFT JOIN LATERAL (
    SELECT x.id, x.kind, x.prompt, x.image, x.expires_at FROM connection_challenges x
    WHERE x.connection_id = c.id AND x.answered_at IS NULL AND x.expires_at > now()
    ORDER BY x.id DESC LIMIT 1
) ch ON true
WHERE c.user_id = $1
ORDER BY c.created_at, c.id
`

type ListUserConnectionsRow struct {
	ID                 int64
	BookID             int64
	BookName           string
	Connector          string
	Label              string
	Enabled            bool
	IntervalHours      int16
	Status             string
	LastError          string
	LastRunAt          *time.Time
	RunRequestedAt     *time.Time
	CreatedAt          time.Time
	KeyRetired         bool
	ChallengeID        int64
	ChallengeKind      string
	ChallengePrompt    string
	ChallengeImage     []byte
	ChallengeExpiresAt time.Time
}

// A person's connections, never with the sealed blob, and with the one open
// challenge (if any) the runner is waiting on.
func (q *Queries) ListUserConnections(ctx context.Context, userID int64) ([]ListUserConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listUserConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserConnectionsRow{}
	for rows.Next() {
		var i ListUserConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.BookName,
			&i.Connector,
			&i.Label,
			&i.Enabled,
			&i.IntervalHours,
			&i.Status,
			&i.LastError,
			&i.LastRunAt,
			&i.RunRequestedAt,
			&i.CreatedAt,
			&i.KeyRetired,
			&i.ChallengeID,
			&i.ChallengeKind,
			&i.ChallengePrompt,
			&i.ChallengeImage,
			&i.ChallengeExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceCredentials = `-- name: ReplaceCredentials :execrows
UPDATE connections SET sealed = $1, key_id = $2, status = 'new', last_error = '', updated_at = now()
WHERE id = $3 AND user_id = $4
`

type ReplaceCredentialsParams struct {
	Sealed []byte
	KeyID  int64
	ID     int64
	UserID int64
}

func (q *Queries) ReplaceCredentials(ctx context.Context, arg ReplaceCredentialsParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceCredentials,
		arg.Sealed,
		arg.KeyID,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestRun = `-- name: RequestRun :execrows
UPDATE connections SET run_requested_at = now() WHERE id = $1 AND user_id = $2 AND enabled
`

type RequestRunParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) RequestRun(ctx context.Context, arg RequestRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, requestRun, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireRunnerKeysExcept = `-- name: RetireRunnerKeysExcept :exec
UPDATE runner_keys SET retired_at = now() WHERE retired_at IS NULL AND NOT (id = ANY($1::BIGINT[]))
`

// The runner declares every key it still holds; the rest are retired.
func (q *Queries) RetireRunnerKeysExcept(ctx context.Context, keep []int64) error {
	_, err := q.db.Exec(ctx, retireRunnerKeysExcept, keep)
	return err
}

const setConnectionStatus = `-- name: SetConnectionStatus :exec
UPDATE connections SET status = $1 WHERE id = $2
`

type SetConnectionStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) SetConnectionStatus(ctx context.Context, arg SetConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, setConnectionStatus, arg.Status, arg.ID)
	return err
}

const takeChallengeAnswer = `-- name: TakeChallengeAnswer :one
WITH old AS (
    SELECT ch.id, ch.answer_sealed FROM connection_challenges ch
    WHERE ch.id = $1 AND ch.connection_id = $2
    FOR UPDATE
)
UPDATE connection_challenges ch SET answer_sealed = NULL
FROM old WHERE ch.id = old.id
RETURNING old.answer_sealed, ch.answered_at, ch.expires_at
`

type TakeChallengeAnswerParams struct {
	ID           int64
	ConnectionID int64
}

type TakeChallengeAnswerRow struct {
	AnswerSealed []byte
	AnsweredAt   *time.Time
	ExpiresAt    time.Time
}

// The runner reads an answer once; it is cleared as it is read.
func (q *Queries) TakeChallengeAnswer(ctx context.Context, arg TakeChallengeAnswerParams) (TakeChallengeAnswerRow, error) {
	row := q.db.QueryRow(ctx, takeChallengeAnswer, arg.ID, arg.ConnectionID)
	var i TakeChallengeAnswerRow
	err := row.Scan(&i.AnswerSealed, &i.AnsweredAt, &i.ExpiresAt)
	return i, err
}

const updateConnection = `-- name: UpdateConnection :execrows
UPDATE connections SET book_id = $1, label = $2, enabled = $3, interval_hours = $4,
    updated_at = now()
WHERE id = $5 AND user_id = $6
`

type UpdateConnectionParams struct {
	BookID        int64
	Label         string
	Enabled       bool
	IntervalHours int16
	ID            int64
	UserID        int64
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConnection,
		arg.BookID,
		arg.Label,
		arg.Enabled,
		arg.IntervalHours,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertConnector = `-- name: UpsertConnector :exec
INSERT INTO runner_connectors (id, name, country, fields) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, country = EXCLUDED.country, fields = EXCLUDED.fields, updated_at = now()
`

type UpsertConnectorParams struct {
	ID      string
	Name    string
	Country string
	Fields  []byte
}

func (q *Queries) UpsertConnector(ctx context.Context, arg UpsertConnectorParams) error {
	_, err := q.db.Exec(ctx, upsertConnector,
		arg.ID,
		arg.Name,
		arg.Country,
		arg.Fields,
	)
	return err
}

const upsertRunnerKey = `-- name: UpsertRunnerKey :one

INSERT INTO runner_keys (public_key) VALUES ($1)
ON CONFLICT (public_key) DO UPDATE SET retired_at = NULL
RETURNING id, public_key, created_at, retired_at
`

// ---------------------------------------------------------------------------
// Runner side
// ---------------------------------------------------------------------------
func (q *Queries) UpsertRunnerKey(ctx context.Context, publicKey []byte) (RunnerKey, error) {
	row := q.db.QueryRow(ctx, upsertRunnerKey, publicKey)
	var i RunnerKey
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}
