// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_tokens.sql

package db

import (
	"context"
	"time"
)

const bumpEmailTokenAttempts = `-- name: BumpEmailTokenAttempts :one
UPDATE email_tokens SET attempts = attempts + 1 WHERE id = $1 RETURNING attempts
`

func (q *Queries) BumpEmailTokenAttempts(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, bumpEmailTokenAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const countRecentEmailTokens = `-- name: CountRecentEmailTokens :one
SELECT count(*) FROM email_tokens
WHERE user_id = $1 AND kind = $2
  AND created_at > now() - make_interval(secs => $3::BIGINT)
`

type CountRecentEmailTokensParams struct {
	UserID        *int64
	Kind          string
	WindowSeconds int64
}

// How many codes or links of a kind were sent to a user lately: the resend cap.
func (q *Queries) CountRecentEmailTokens(ctx context.Context, arg CountRecentEmailTokensParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentEmailTokens, arg.UserID, arg.Kind, arg.WindowSeconds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO email_tokens (user_id, kind, email, token_hash, code_hash, payload, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8)
RETURNING id, user_id, kind, email, token_hash, code_hash, payload, attempts, expires_at, used_at, created_by, created_at
`

type CreateEmailTokenParams struct {
	UserID    *int64
	Kind      string
	Email     string
	TokenHash []byte
	CodeHash  []byte
	Payload   []byte
	ExpiresAt time.Time
	CreatedBy *int64
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, createEmailToken,
		arg.UserID,
		arg.Kind,
		arg.Email,
		arg.TokenHash,
		arg.CodeHash,
		arg.Payload,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Email,
		&i.TokenHash,
		&i.CodeHash,
		&i.Payload,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStaleEmailTokens = `-- name: DeleteStaleEmailTokens :execrows
DELETE FROM email_tokens WHERE expires_at < now() - INTERVAL '30 days'
`

func (q *Queries) DeleteStaleEmailTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleEmailTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailToken = `-- name: GetEmailToken :one
SELECT id, user_id, kind, email, token_hash, code_hash, payload, attempts, expires_at, used_at, created_by, created_at FROM email_tokens WHERE id = $1
`

func (q *Queries) GetEmailToken(ctx context.Context, id int64) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getEmailToken, id)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Email,
		&i.TokenHash,
		&i.CodeHash,
		&i.Payload,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailTokenByHash = `-- name: GetEmailTokenByHash :one
SELECT id, user_id, kind, email, token_hash, code_hash, payload, attempts, expires_at, used_at, created_by, created_at FROM email_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

// A link token that can still be used.
func (q *Queries) GetEmailTokenByHash(ctx context.Context, tokenHash []byte) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getEmailTokenByHash, tokenHash)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Email,
		&i.TokenHash,
		&i.CodeHash,
		&i.Payload,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenEmailToken = `-- name: GetOpenEmailToken :one
SELECT id, user_id, kind, email, token_hash, code_hash, payload, attempts, expires_at, used_at, created_by, created_at FROM email_tokens
WHERE user_id = $1 AND kind = $2 AND used_at IS NULL AND expires_at > now()
ORDER BY id DESC
LIMIT 1
`

type GetOpenEmailTokenParams struct {
	UserID *int64
	Kind   string
}

// The newest open token of a kind for a user (the pending email change, the
// open invitation).
func (q *Queries) GetOpenEmailToken(ctx context.Context, arg GetOpenEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getOpenEmailToken, arg.UserID, arg.Kind)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Email,
		&i.TokenHash,
		&i.CodeHash,
		&i.Payload,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const openRegistrationExists = `-- name: OpenRegistrationExists :one
SELECT EXISTS (
    SELECT 1 FROM email_tokens
    WHERE kind = 'register' AND used_at IS NULL AND expires_at > now()
      AND (lower(email) = lower($1) OR payload ->> 'username' = $2::TEXT)
)
`

type OpenRegistrationExistsParams struct {
	Email    string
	Username string
}

// Another sign-up still waiting for its link with this username or address.
func (q *Queries) OpenRegistrationExists(ctx context.Context, arg OpenRegistrationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, openRegistrationExists, arg.Email, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeEmailTokens = `-- name: RevokeEmailTokens :exec
UPDATE email_tokens SET used_at = now()
WHERE user_id = $1 AND kind = $2 AND used_at IS NULL
`

type RevokeEmailTokensParams struct {
	UserID *int64
	Kind   string
}

// Closing a kind for a user: a new code replaces the old, a revoked
// invitation stops working.
func (q *Queries) RevokeEmailTokens(ctx context.Context, arg RevokeEmailTokensParams) error {
	_, err := q.db.Exec(ctx, revokeEmailTokens, arg.UserID, arg.Kind)
	return err
}

const useEmailToken = `-- name: UseEmailToken :execrows
UPDATE email_tokens SET used_at = now() WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) UseEmailToken(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, useEmailToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
