// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const accountDrift = `-- name: AccountDrift :many
SELECT DISTINCT ON (ba.account_id)
       ba.account_id, ba.date, ba.amount AS asserted, ba.source,
       coalesce((SELECT sum(p.amount) FROM postings p JOIN transactions t ON t.id = p.transaction_id
                 WHERE p.account_id = ba.account_id AND t.date <= ba.date), 0)::numeric AS booked
FROM balance_assertions ba
WHERE ba.book_id = $1
ORDER BY ba.account_id, ba.date DESC, ba.created_at DESC
`

type AccountDriftRow struct {
	AccountID int64
	Date      time.Time
	Asserted  decimal.Decimal
	Source    string
	Booked    decimal.Decimal
}

// The newest assertion of each account against what the books say on that
// date (in the account's own commodity).
func (q *Queries) AccountDrift(ctx context.Context, bookID int64) ([]AccountDriftRow, error) {
	rows, err := q.db.Query(ctx, accountDrift, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountDriftRow{}
	for rows.Next() {
		var i AccountDriftRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Date,
			&i.Asserted,
			&i.Source,
			&i.Booked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batches (book_id, connector, label, created_by) VALUES ($1, $2, $3, $4)
RETURNING id, book_id, connector, label, received, duplicates, created_by, created_at
`

type CreateImportBatchParams struct {
	BookID    int64
	Connector string
	Label     string
	CreatedBy *int64
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.BookID,
		arg.Connector,
		arg.Label,
		arg.CreatedBy,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Connector,
		&i.Label,
		&i.Received,
		&i.Duplicates,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createRule = `-- name: CreateRule :one
INSERT INTO import_rules (book_id, priority, pattern, source_account_id, account_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, book_id, priority, pattern, source_account_id, account_id, created_by, created_at
`

type CreateRuleParams struct {
	BookID          int64
	Priority        int32
	Pattern         string
	SourceAccountID *int64
	AccountID       int64
	CreatedBy       *int64
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (ImportRule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.BookID,
		arg.Priority,
		arg.Pattern,
		arg.SourceAccountID,
		arg.AccountID,
		arg.CreatedBy,
	)
	var i ImportRule
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Priority,
		&i.Pattern,
		&i.SourceAccountID,
		&i.AccountID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const decideRow = `-- name: DecideRow :execrows
UPDATE import_rows SET status = $1, transaction_id = $2,
    decided_by = $3, decided_at = now()
WHERE id = $4 AND status = 'pending'
`

type DecideRowParams struct {
	Status        string
	TransactionID *int64
	DecidedBy     *int64
	ID            int64
}

func (q *Queries) DecideRow(ctx context.Context, arg DecideRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideRow,
		arg.Status,
		arg.TransactionID,
		arg.DecidedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRule = `-- name: DeleteRule :execrows
DELETE FROM import_rules WHERE book_id = $1 AND id = $2
`

type DeleteRuleParams struct {
	BookID int64
	ID     int64
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRule, arg.BookID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findDuplicate = `-- name: FindDuplicate :one
SELECT t.id FROM postings p JOIN transactions t ON t.id = p.transaction_id
WHERE t.book_id = $1 AND p.account_id = $2 AND p.amount = $3
  AND t.date BETWEEN $4 AND $5
  AND NOT EXISTS (SELECT 1 FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
                  WHERE r.book_id = $1 AND r.status <> 'ignored' AND s.account_id = $2
                    AND (r.transaction_id = t.id OR r.match_transaction_id = t.id))
ORDER BY abs(t.date - $6::DATE), t.id
LIMIT 1
`

type FindDuplicateParams struct {
	BookID    int64
	AccountID int64
	Amount    decimal.Decimal
	FromDate  time.Time
	ToDate    time.Time
	OnDate    time.Time
}

// A transaction already in the books for this row: same account, same
// amount, within a few days, not already claimed by a row of this account
// (a typed-in transfer is claimed once from each side).
func (q *Queries) FindDuplicate(ctx context.Context, arg FindDuplicateParams) (int64, error) {
	row := q.db.QueryRow(ctx, findDuplicate,
		arg.BookID,
		arg.AccountID,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findDuplicateRow = `-- name: FindDuplicateRow :one
SELECT r.id, r.pending FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
WHERE r.book_id = $1 AND r.status = 'pending' AND r.kind = 'transaction' AND r.id <> $2
  AND s.account_id = $3 AND r.source_account_id <> $4
  AND r.currency = $5 AND r.amount = $6 AND r.date BETWEEN $7 AND $8
  AND (r.match_row_id IS NULL OR r.match_row_id = $2)
  AND NOT EXISTS (SELECT 1 FROM import_rows o WHERE o.book_id = $1 AND o.status = 'pending' AND o.id <> $2
                  AND o.proposal = 'duplicate' AND o.match_row_id = r.id)
ORDER BY abs(r.date - $9::DATE), r.id
LIMIT 1
`

type FindDuplicateRowParams struct {
	BookID          int64
	RowID           int64
	AccountID       *int64
	SourceAccountID int64
	Currency        string
	Amount          decimal.Decimal
	FromDate        time.Time
	ToDate          time.Time
	OnDate          time.Time
}

type FindDuplicateRowRow struct {
	ID      int64
	Pending bool
}

// The same charge waiting from another source: a pending transaction row
// on the same ledger account, the same amount and currency, a few days
// apart, from another source account (one source's two identical coffees
// are two), not already paired with a third.
func (q *Queries) FindDuplicateRow(ctx context.Context, arg FindDuplicateRowParams) (FindDuplicateRowRow, error) {
	row := q.db.QueryRow(ctx, findDuplicateRow,
		arg.BookID,
		arg.RowID,
		arg.AccountID,
		arg.SourceAccountID,
		arg.Currency,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.OnDate,
	)
	var i FindDuplicateRowRow
	err := row.Scan(&i.ID, &i.Pending)
	return i, err
}

const findEstimate = `-- name: FindEstimate :one
SELECT t.id FROM postings p JOIN transactions t ON t.id = p.transaction_id
WHERE t.book_id = $1 AND p.account_id = $2 AND p.status = 'uncleared'
  AND p.amount BETWEEN $3 AND $4
  AND t.date BETWEEN $5 AND $6
  AND (SELECT count(*) FROM postings x WHERE x.transaction_id = t.id) = 2
  AND NOT EXISTS (SELECT 1 FROM import_rows r WHERE r.book_id = $1 AND r.status = 'pending'
                  AND r.match_transaction_id = t.id)
ORDER BY abs(p.amount - $7::NUMERIC), abs(t.date - $8::DATE), t.id
LIMIT 1
`

type FindEstimateParams struct {
	BookID    int64
	AccountID int64
	Lo        decimal.Decimal
	Hi        decimal.Decimal
	FromDate  time.Time
	ToDate    time.Time
	Amount    decimal.Decimal
	OnDate    time.Time
}

// An uncleared entry this posted row settles: same account and sign, the
// amount within the tolerance, a few days either side (a card charge
// entered as an estimate, or a pending row accepted earlier).
func (q *Queries) FindEstimate(ctx context.Context, arg FindEstimateParams) (int64, error) {
	row := q.db.QueryRow(ctx, findEstimate,
		arg.BookID,
		arg.AccountID,
		arg.Lo,
		arg.Hi,
		arg.FromDate,
		arg.ToDate,
		arg.Amount,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findForeignPaymentRows = `-- name: FindForeignPaymentRows :many
SELECT r.id, r.description, r.counterparty, r.amount, r.currency FROM import_rows r
JOIN commodities c ON c.code = r.currency AND c.kind = 'currency'
WHERE r.book_id = $1 AND r.status = 'pending' AND r.kind = 'transaction'
  AND r.currency <> $2 AND sign(r.amount) = sign($3::NUMERIC)
  AND r.date BETWEEN $4 AND $5
  AND NOT EXISTS (SELECT 1 FROM import_rows o WHERE o.book_id = $1 AND o.kind = 'invoice' AND o.status = 'pending'
                  AND o.amount <> 0 AND o.match_row_id = r.id AND o.id <> $6)
ORDER BY abs(r.date - $7::DATE), r.id
LIMIT 50
`

type FindForeignPaymentRowsParams struct {
	BookID   int64
	Currency string
	Amount   decimal.Decimal
	FromDate time.Time
	ToDate   time.Time
	RowID    int64
	OnDate   time.Time
}

type FindForeignPaymentRowsRow struct {
	ID           int64
	Description  string
	Counterparty string
	Amount       decimal.Decimal
	Currency     string
}

// The same, among card and bank rows still waiting.
func (q *Queries) FindForeignPaymentRows(ctx context.Context, arg FindForeignPaymentRowsParams) ([]FindForeignPaymentRowsRow, error) {
	rows, err := q.db.Query(ctx, findForeignPaymentRows,
		arg.BookID,
		arg.Currency,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.RowID,
		arg.OnDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindForeignPaymentRowsRow{}
	for rows.Next() {
		var i FindForeignPaymentRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Counterparty,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findForeignPayments = `-- name: FindForeignPayments :many
SELECT t.id, t.payee, t.memo, p.amount, p.commodity FROM postings p
JOIN transactions t ON t.id = p.transaction_id
JOIN accounts a ON a.id = p.account_id
JOIN commodities c ON c.code = p.commodity AND c.kind = 'currency'
WHERE t.book_id = $1 AND a.class IN ('asset', 'liability')
  AND p.commodity <> $2 AND sign(p.amount) = sign($3::NUMERIC)
  AND t.date BETWEEN $4 AND $5
  AND NOT EXISTS (SELECT 1 FROM transaction_items i WHERE i.transaction_id = t.id)
  AND NOT EXISTS (SELECT 1 FROM import_rows o WHERE o.book_id = $1 AND o.kind = 'invoice' AND o.status = 'pending'
                  AND o.amount <> 0 AND o.match_transaction_id = t.id AND o.id <> $6)
ORDER BY abs(t.date - $7::DATE), t.id
LIMIT 50
`

type FindForeignPaymentsParams struct {
	BookID   int64
	Currency string
	Amount   decimal.Decimal
	FromDate time.Time
	ToDate   time.Time
	RowID    int64
	OnDate   time.Time
}

type FindForeignPaymentsRow struct {
	ID        int64
	Payee     string
	Memo      string
	Amount    decimal.Decimal
	Commodity string
}

// Payments in another currency than an invoice, in its window, the same
// way (out or in): candidates for an invoice billed in EUR and charged in
// TWD. The caller checks the amount at the day's rate and the payee.
func (q *Queries) FindForeignPayments(ctx context.Context, arg FindForeignPaymentsParams) ([]FindForeignPaymentsRow, error) {
	rows, err := q.db.Query(ctx, findForeignPayments,
		arg.BookID,
		arg.Currency,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.RowID,
		arg.OnDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindForeignPaymentsRow{}
	for rows.Next() {
		var i FindForeignPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Payee,
			&i.Memo,
			&i.Amount,
			&i.Commodity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findInvoiceByReference = `-- name: FindInvoiceByReference :one
SELECT i.transaction_id FROM transaction_items i
WHERE i.book_id = $1 AND i.source NOT LIKE $2::TEXT || ':%'
  AND (i.source LIKE '%:' || $3::TEXT || ':%' OR i.source LIKE '%:' || $3::TEXT)
ORDER BY i.transaction_id DESC
LIMIT 1
`

type FindInvoiceByReferenceParams struct {
	BookID    int64
	Connector string
	Reference string
}

// The payment that already carries the lines of the invoice with this
// number, from another source (the 電子發票 an Apple email names).
func (q *Queries) FindInvoiceByReference(ctx context.Context, arg FindInvoiceByReferenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, findInvoiceByReference, arg.BookID, arg.Connector, arg.Reference)
	var transaction_id int64
	err := row.Scan(&transaction_id)
	return transaction_id, err
}

const findInvoiceMatch = `-- name: FindInvoiceMatch :one
SELECT t.id FROM postings p
JOIN transactions t ON t.id = p.transaction_id
JOIN accounts a ON a.id = p.account_id
WHERE t.book_id = $1 AND a.class IN ('asset', 'liability')
  AND p.commodity = $2 AND p.amount = $3
  AND t.date BETWEEN $4 AND $5
  AND NOT EXISTS (SELECT 1 FROM transaction_items i WHERE i.transaction_id = t.id)
  AND NOT EXISTS (SELECT 1 FROM import_rows o WHERE o.book_id = $1 AND o.kind = 'invoice' AND o.status = 'pending'
                  AND o.amount <> 0 AND o.match_transaction_id = t.id AND o.id <> $6)
ORDER BY ($7::TEXT <> '' AND t.payee ILIKE '%' || $7::TEXT || '%') DESC, abs(t.date - $8::DATE), t.id
LIMIT 1
`

type FindInvoiceMatchParams struct {
	BookID   int64
	Currency string
	Amount   decimal.Decimal
	FromDate time.Time
	ToDate   time.Time
	RowID    int64
	Seller   string
	OnDate   time.Time
}

// The booked payment an invoice belongs to: a card, bank or cash line of
// its total, from two days before to five after (a card posts late), on a
// transaction that has no invoice yet and that no other waiting invoice
// claims. The seller's name in the payee wins a tie, then the nearest day.
func (q *Queries) FindInvoiceMatch(ctx context.Context, arg FindInvoiceMatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, findInvoiceMatch,
		arg.BookID,
		arg.Currency,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.RowID,
		arg.Seller,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findInvoiceRow = `-- name: FindInvoiceRow :one
SELECT r.id FROM import_rows r
WHERE r.book_id = $1 AND r.status = 'pending' AND r.kind = 'transaction'
  AND r.currency = $2 AND r.amount = $3 AND r.date BETWEEN $4 AND $5
  AND NOT EXISTS (SELECT 1 FROM import_rows o WHERE o.book_id = $1 AND o.kind = 'invoice' AND o.status = 'pending'
                  AND o.amount <> 0 AND o.match_row_id = r.id AND o.id <> $6)
ORDER BY ($7::TEXT <> '' AND (r.description ILIKE '%' || $7::TEXT || '%' OR r.counterparty ILIKE '%' || $7::TEXT || '%')) DESC,
         abs(r.date - $8::DATE), r.id
LIMIT 1
`

type FindInvoiceRowParams struct {
	BookID   int64
	Currency string
	Amount   decimal.Decimal
	FromDate time.Time
	ToDate   time.Time
	RowID    int64
	Seller   string
	OnDate   time.Time
}

// A card or bank row still waiting in the queue that will pay for it.
func (q *Queries) FindInvoiceRow(ctx context.Context, arg FindInvoiceRowParams) (int64, error) {
	row := q.db.QueryRow(ctx, findInvoiceRow,
		arg.BookID,
		arg.Currency,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.RowID,
		arg.Seller,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findInvoiceRowByReference = `-- name: FindInvoiceRowByReference :one
SELECT o.id FROM import_rows o JOIN source_accounts s ON s.id = o.source_account_id
WHERE o.book_id = $1 AND o.status = 'pending' AND o.kind = 'invoice' AND o.id <> $2
  AND s.connector <> $3 AND o.amount <> 0 AND (o.id < $2 OR $4::BOOLEAN)
  AND (o.external_id LIKE '%:' || $5::TEXT || ':%' OR o.external_id LIKE '%:' || $5::TEXT
       OR o.reference = $5::TEXT)
ORDER BY o.id
LIMIT 1
`

type FindInvoiceRowByReferenceParams struct {
	BookID    int64
	RowID     int64
	Connector string
	AnyOrder  bool
	Reference string
}

// That invoice still waiting in the queue: an earlier one, or any when this
// row states no amount (it never waits the other way, so they never wait on
// each other).
func (q *Queries) FindInvoiceRowByReference(ctx context.Context, arg FindInvoiceRowByReferenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, findInvoiceRowByReference,
		arg.BookID,
		arg.RowID,
		arg.Connector,
		arg.AnyOrder,
		arg.Reference,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findPaymentRowsNamed = `-- name: FindPaymentRowsNamed :many
SELECT r.id, r.description, r.counterparty FROM import_rows r
WHERE r.book_id = $1 AND r.status = 'pending' AND r.kind = 'transaction' AND r.amount < 0
  AND r.date BETWEEN $2 AND $3
ORDER BY abs(r.date - $4::DATE), r.id
LIMIT 100
`

type FindPaymentRowsNamedParams struct {
	BookID   int64
	FromDate time.Time
	ToDate   time.Time
	OnDate   time.Time
}

type FindPaymentRowsNamedRow struct {
	ID           int64
	Description  string
	Counterparty string
}

func (q *Queries) FindPaymentRowsNamed(ctx context.Context, arg FindPaymentRowsNamedParams) ([]FindPaymentRowsNamedRow, error) {
	rows, err := q.db.Query(ctx, findPaymentRowsNamed,
		arg.BookID,
		arg.FromDate,
		arg.ToDate,
		arg.OnDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPaymentRowsNamedRow{}
	for rows.Next() {
		var i FindPaymentRowsNamedRow
		if err := rows.Scan(&i.ID, &i.Description, &i.Counterparty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPaymentsNamed = `-- name: FindPaymentsNamed :many
SELECT t.id, t.payee, t.memo FROM postings p
JOIN transactions t ON t.id = p.transaction_id
JOIN accounts a ON a.id = p.account_id
WHERE t.book_id = $1 AND a.class IN ('asset', 'liability') AND p.amount < 0
  AND t.date BETWEEN $2 AND $3
ORDER BY abs(t.date - $4::DATE), t.id
LIMIT 100
`

type FindPaymentsNamedParams struct {
	BookID   int64
	FromDate time.Time
	ToDate   time.Time
	OnDate   time.Time
}

type FindPaymentsNamedRow struct {
	ID    int64
	Payee string
	Memo  string
}

// Money out in a window, whatever its amount or currency: candidates for an
// email that states none. The caller checks the payee names the seller.
func (q *Queries) FindPaymentsNamed(ctx context.Context, arg FindPaymentsNamedParams) ([]FindPaymentsNamedRow, error) {
	rows, err := q.db.Query(ctx, findPaymentsNamed,
		arg.BookID,
		arg.FromDate,
		arg.ToDate,
		arg.OnDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPaymentsNamedRow{}
	for rows.Next() {
		var i FindPaymentsNamedRow
		if err := rows.Scan(&i.ID, &i.Payee, &i.Memo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSameInvoiceRow = `-- name: FindSameInvoiceRow :one
SELECT o.id FROM import_rows o JOIN source_accounts s ON s.id = o.source_account_id
WHERE o.book_id = $1 AND o.status = 'pending' AND o.kind = 'invoice' AND o.id < $2
  AND s.connector <> $3 AND o.currency = $4 AND o.amount = $5
  AND o.date BETWEEN $6 AND $7 AND o.proposal IN ('enrich', 'new', 'waiting')
ORDER BY abs(o.date - $8::DATE), o.id
LIMIT 1
`

type FindSameInvoiceRowParams struct {
	BookID    int64
	RowID     int64
	Connector string
	Currency  string
	Amount    decimal.Decimal
	FromDate  time.Time
	ToDate    time.Time
	OnDate    time.Time
}

// Another source's invoice for it, still waiting and staged earlier: the
// first keeps its proposal, so two never wait on each other.
func (q *Queries) FindSameInvoiceRow(ctx context.Context, arg FindSameInvoiceRowParams) (int64, error) {
	row := q.db.QueryRow(ctx, findSameInvoiceRow,
		arg.BookID,
		arg.RowID,
		arg.Connector,
		arg.Currency,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findSameInvoiceTx = `-- name: FindSameInvoiceTx :one
SELECT t.id FROM postings p
JOIN transactions t ON t.id = p.transaction_id
JOIN accounts a ON a.id = p.account_id
WHERE t.book_id = $1 AND a.class IN ('asset', 'liability')
  AND p.commodity = $2 AND p.amount = $3
  AND t.date BETWEEN $4 AND $5
  AND EXISTS (SELECT 1 FROM transaction_items i WHERE i.transaction_id = t.id AND i.source NOT LIKE $6::TEXT || ':%')
ORDER BY abs(t.date - $7::DATE), t.id
LIMIT 1
`

type FindSameInvoiceTxParams struct {
	BookID    int64
	Currency  string
	Amount    decimal.Decimal
	FromDate  time.Time
	ToDate    time.Time
	Connector string
	OnDate    time.Time
}

// A payment another source's invoice already added its lines to: a card,
// bank or cash line of this total, in the window, carrying items from a
// connector that is not this one.
func (q *Queries) FindSameInvoiceTx(ctx context.Context, arg FindSameInvoiceTxParams) (int64, error) {
	row := q.db.QueryRow(ctx, findSameInvoiceTx,
		arg.BookID,
		arg.Currency,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.Connector,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findSecurityChild = `-- name: FindSecurityChild :one
SELECT id FROM accounts
WHERE book_id = $1 AND parent_id = $2 AND commodity = $3
  AND NOT is_placeholder AND archived_at IS NULL
ORDER BY id
LIMIT 1
`

type FindSecurityChildParams struct {
	BookID    int64
	ParentID  *int64
	Commodity *string
}

// The account a parent already has for a security: another source of the
// same broker account made it (集保 and Shioaji share "2330 台積電").
func (q *Queries) FindSecurityChild(ctx context.Context, arg FindSecurityChildParams) (int64, error) {
	row := q.db.QueryRow(ctx, findSecurityChild, arg.BookID, arg.ParentID, arg.Commodity)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findTradeDuplicate = `-- name: FindTradeDuplicate :one
SELECT t.id FROM postings p JOIN transactions t ON t.id = p.transaction_id
WHERE t.book_id = $1 AND p.account_id = $2 AND p.amount = $3
  AND t.date BETWEEN $4 AND $5
  AND NOT EXISTS (SELECT 1 FROM import_rows r
                  WHERE r.book_id = $1 AND r.kind = 'trade' AND r.status <> 'ignored' AND r.id <> $6
                    AND (r.transaction_id = t.id OR r.match_transaction_id = t.id))
ORDER BY abs(t.date - $7::DATE), t.id
LIMIT 1
`

type FindTradeDuplicateParams struct {
	BookID    int64
	AccountID int64
	Units     decimal.Decimal
	FromDate  time.Time
	ToDate    time.Time
	RowID     int64
	OnDate    time.Time
}

// A trade already in the books: the same units on the security's account,
// within a few days, not already claimed by another trade row.
func (q *Queries) FindTradeDuplicate(ctx context.Context, arg FindTradeDuplicateParams) (int64, error) {
	row := q.db.QueryRow(ctx, findTradeDuplicate,
		arg.BookID,
		arg.AccountID,
		arg.Units,
		arg.FromDate,
		arg.ToDate,
		arg.RowID,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findTradeRow = `-- name: FindTradeRow :one
SELECT r.id, (r.cash IS NOT NULL)::BOOLEAN AS has_cash FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
WHERE r.book_id = $1 AND r.status = 'pending' AND r.kind = 'trade' AND r.id <> $2
  AND s.account_id = $3 AND r.source_account_id <> $4
  AND r.security = $5 AND r.units = $6 AND r.date BETWEEN $7 AND $8
  AND (r.match_row_id IS NULL OR r.match_row_id = $2)
  AND NOT EXISTS (SELECT 1 FROM import_rows o WHERE o.book_id = $1 AND o.status = 'pending' AND o.id <> $2
                  AND o.proposal = 'duplicate' AND o.match_row_id = r.id)
ORDER BY abs(r.date - $9::DATE), r.id
LIMIT 1
`

type FindTradeRowParams struct {
	BookID          int64
	RowID           int64
	AccountID       *int64
	SourceAccountID int64
	Security        *string
	Units           decimal.NullDecimal
	FromDate        time.Time
	ToDate          time.Time
	OnDate          time.Time
}

type FindTradeRowRow struct {
	ID      int64
	HasCash bool
}

// The same trade waiting from another source of the same broker account
// (mapped to the same parent): the same security and units, a few days
// apart, not already paired with a third.
func (q *Queries) FindTradeRow(ctx context.Context, arg FindTradeRowParams) (FindTradeRowRow, error) {
	row := q.db.QueryRow(ctx, findTradeRow,
		arg.BookID,
		arg.RowID,
		arg.AccountID,
		arg.SourceAccountID,
		arg.Security,
		arg.Units,
		arg.FromDate,
		arg.ToDate,
		arg.OnDate,
	)
	var i FindTradeRowRow
	err := row.Scan(&i.ID, &i.HasCash)
	return i, err
}

const findTransferByReference = `-- name: FindTransferByReference :one
SELECT r.id FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
WHERE r.book_id = $1 AND r.status = 'pending' AND r.kind = 'transaction' AND r.id <> $2
  AND s.account_id IS NOT NULL AND s.account_id <> $3
  AND r.reference = $4::TEXT AND r.currency <> $5 AND sign(r.amount) = -sign($6::NUMERIC)
  AND r.date BETWEEN $7 AND $8
  AND r.proposal IN ('new', 'transfer') AND (r.match_row_id IS NULL OR r.match_row_id = $2)
ORDER BY abs(r.date - $9::DATE), r.id
LIMIT 1
`

type FindTransferByReferenceParams struct {
	BookID    int64
	RowID     int64
	AccountID *int64
	Reference string
	Currency  string
	Amount    decimal.Decimal
	FromDate  time.Time
	ToDate    time.Time
	OnDate    time.Time
}

// The other side of an exchange between two of the book's accounts in two
// currencies (USD sold, PYG bought): the bank gives both the same movement
// number. Opposite directions, a few days apart, not already paired.
func (q *Queries) FindTransferByReference(ctx context.Context, arg FindTransferByReferenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, findTransferByReference,
		arg.BookID,
		arg.RowID,
		arg.AccountID,
		arg.Reference,
		arg.Currency,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findTransferPartner = `-- name: FindTransferPartner :one
SELECT r.id FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
WHERE r.book_id = $1 AND r.status = 'pending' AND r.kind = 'transaction' AND r.id <> $2
  AND s.account_id IS NOT NULL AND s.account_id <> $3
  AND r.currency = $4 AND r.amount + $5::NUMERIC = 0
  AND r.date BETWEEN $6 AND $7
  AND r.proposal IN ('new', 'transfer') AND (r.match_row_id IS NULL OR r.match_row_id = $2)
ORDER BY abs(r.date - $8::DATE), r.id
LIMIT 1
`

type FindTransferPartnerParams struct {
	BookID    int64
	RowID     int64
	AccountID *int64
	Currency  string
	Amount    decimal.Decimal
	FromDate  time.Time
	ToDate    time.Time
	OnDate    time.Time
}

// The other side of a transfer between two of the book's own accounts:
// another pending row, from another mapped account, the opposite amount in
// the same currency, a few days apart, not already paired.
func (q *Queries) FindTransferPartner(ctx context.Context, arg FindTransferPartnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, findTransferPartner,
		arg.BookID,
		arg.RowID,
		arg.AccountID,
		arg.Currency,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getImportRow = `-- name: GetImportRow :one
SELECT r.id, r.book_id, r.batch_id, r.source_account_id, r.kind, r.external_id, r.date, r.amount, r.currency, r.description, r.counterparty, r.pending, r.raw, r.proposal, r.proposed_account_id, r.match_transaction_id, r.match_row_id, r.rule_id, r.status, r.transaction_id, r.decided_by, r.decided_at, r.created_at, r.attachment_id, r.security, r.units, r.price, r.cash, r.items, r.reference, s.account_id, s.connector, s.settlement_account_id, s.ignored AS source_ignored
FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
WHERE r.book_id = $1 AND r.id = $2
`

type GetImportRowParams struct {
	BookID int64
	ID     int64
}

type GetImportRowRow struct {
	ID                  int64
	BookID              int64
	BatchID             int64
	SourceAccountID     int64
	Kind                string
	ExternalID          string
	Date                time.Time
	Amount              decimal.Decimal
	Currency            string
	Description         string
	Counterparty        string
	Pending             bool
	Raw                 []byte
	Proposal            string
	ProposedAccountID   *int64
	MatchTransactionID  *int64
	MatchRowID          *int64
	RuleID              *int64
	Status              string
	TransactionID       *int64
	DecidedBy           *int64
	DecidedAt           *time.Time
	CreatedAt           time.Time
	AttachmentID        *int64
	Security            *string
	Units               decimal.NullDecimal
	Price               decimal.NullDecimal
	Cash                decimal.NullDecimal
	Items               []byte
	Reference           *string
	AccountID           *int64
	Connector           string
	SettlementAccountID *int64
	SourceIgnored       bool
}

func (q *Queries) GetImportRow(ctx context.Context, arg GetImportRowParams) (GetImportRowRow, error) {
	row := q.db.QueryRow(ctx, getImportRow, arg.BookID, arg.ID)
	var i GetImportRowRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.BatchID,
		&i.SourceAccountID,
		&i.Kind,
		&i.ExternalID,
		&i.Date,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Counterparty,
		&i.Pending,
		&i.Raw,
		&i.Proposal,
		&i.ProposedAccountID,
		&i.MatchTransactionID,
		&i.MatchRowID,
		&i.RuleID,
		&i.Status,
		&i.TransactionID,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.AttachmentID,
		&i.Security,
		&i.Units,
		&i.Price,
		&i.Cash,
		&i.Items,
		&i.Reference,
		&i.AccountID,
		&i.Connector,
		&i.SettlementAccountID,
		&i.SourceIgnored,
	)
	return i, err
}

const getSourceAccount = `-- name: GetSourceAccount :one
SELECT id, book_id, connector, external_id, label, currency, account_id, created_at, kind, settlement_account_id, ignored FROM source_accounts WHERE book_id = $1 AND id = $2
`

type GetSourceAccountParams struct {
	BookID int64
	ID     int64
}

func (q *Queries) GetSourceAccount(ctx context.Context, arg GetSourceAccountParams) (SourceAccount, error) {
	row := q.db.QueryRow(ctx, getSourceAccount, arg.BookID, arg.ID)
	var i SourceAccount
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Connector,
		&i.ExternalID,
		&i.Label,
		&i.Currency,
		&i.AccountID,
		&i.CreatedAt,
		&i.Kind,
		&i.SettlementAccountID,
		&i.Ignored,
	)
	return i, err
}

const getSourceSecurity = `-- name: GetSourceSecurity :one
SELECT account_id FROM source_securities WHERE source_account_id = $1 AND commodity = $2
`

type GetSourceSecurityParams struct {
	SourceAccountID int64
	Commodity       string
}

func (q *Queries) GetSourceSecurity(ctx context.Context, arg GetSourceSecurityParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSourceSecurity, arg.SourceAccountID, arg.Commodity)
	var account_id int64
	err := row.Scan(&account_id)
	return account_id, err
}

const insertImportRow = `-- name: InsertImportRow :one
INSERT INTO import_rows (book_id, batch_id, source_account_id, kind, external_id, date, amount, currency,
                         description, counterparty, pending, raw, security, units, price, cash, items, reference)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14, $15, $16,
        $17, $18)
ON CONFLICT (book_id, external_id) DO NOTHING
RETURNING id
`

type InsertImportRowParams struct {
	BookID          int64
	BatchID         int64
	SourceAccountID int64
	Kind            string
	ExternalID      string
	Date            time.Time
	Amount          decimal.Decimal
	Currency        string
	Description     string
	Counterparty    string
	Pending         bool
	Raw             []byte
	Security        *string
	Units           decimal.NullDecimal
	Price           decimal.NullDecimal
	Cash            decimal.NullDecimal
	Items           []byte
	Reference       *string
}

// Nothing on a row already staged (the same external id): that is what
// makes a re-sync harmless. The caller counts the missing RETURNING.
func (q *Queries) InsertImportRow(ctx context.Context, arg InsertImportRowParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportRow,
		arg.BookID,
		arg.BatchID,
		arg.SourceAccountID,
		arg.Kind,
		arg.ExternalID,
		arg.Date,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Counterparty,
		arg.Pending,
		arg.Raw,
		arg.Security,
		arg.Units,
		arg.Price,
		arg.Cash,
		arg.Items,
		arg.Reference,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listQueue = `-- name: ListQueue :many
SELECT r.id, r.kind, r.external_id, r.date, r.amount, r.currency, r.description, r.counterparty, r.pending,
       r.proposal, r.proposed_account_id, r.match_transaction_id, r.match_row_id, r.rule_id, r.attachment_id,
       r.security, c.name AS security_name, r.units, r.price, r.cash, r.items,
       s.id AS source_account_id, s.connector, s.label AS source_label, s.account_id, s.settlement_account_id,
       mp.amount AS match_posting_amount, mp.commodity AS match_posting_currency,
       mr.amount AS match_row_amount, mr.currency AS match_row_currency
FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
LEFT JOIN commodities c ON c.code = r.security
LEFT JOIN postings mp ON mp.id = (SELECT p.id FROM postings p JOIN accounts pa ON pa.id = p.account_id
                                  WHERE p.transaction_id = r.match_transaction_id AND pa.class IN ('asset', 'liability')
                                  ORDER BY p.position LIMIT 1)
LEFT JOIN import_rows mr ON mr.id = r.match_row_id
WHERE r.book_id = $1 AND r.status = 'pending'
ORDER BY r.date DESC, r.id DESC
LIMIT $2
`

type ListQueueParams struct {
	BookID int64
	Lim    int32
}

type ListQueueRow struct {
	ID                   int64
	Kind                 string
	ExternalID           string
	Date                 time.Time
	Amount               decimal.Decimal
	Currency             string
	Description          string
	Counterparty         string
	Pending              bool
	Proposal             string
	ProposedAccountID    *int64
	MatchTransactionID   *int64
	MatchRowID           *int64
	RuleID               *int64
	AttachmentID         *int64
	Security             *string
	SecurityName         *string
	Units                decimal.NullDecimal
	Price                decimal.NullDecimal
	Cash                 decimal.NullDecimal
	Items                []byte
	SourceAccountID      int64
	Connector            string
	SourceLabel          string
	AccountID            *int64
	SettlementAccountID  *int64
	MatchPostingAmount   decimal.NullDecimal
	MatchPostingCurrency *string
	MatchRowAmount       decimal.NullDecimal
	MatchRowCurrency     *string
}

// The review queue: pending rows with their source account's mapping.
// What a row matched, for the queue to show beside it (an invoice in EUR
// beside the TWD charge it enriches): the payment's line, or the other row.
func (q *Queries) ListQueue(ctx context.Context, arg ListQueueParams) ([]ListQueueRow, error) {
	rows, err := q.db.Query(ctx, listQueue, arg.BookID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueueRow{}
	for rows.Next() {
		var i ListQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ExternalID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Counterparty,
			&i.Pending,
			&i.Proposal,
			&i.ProposedAccountID,
			&i.MatchTransactionID,
			&i.MatchRowID,
			&i.RuleID,
			&i.AttachmentID,
			&i.Security,
			&i.SecurityName,
			&i.Units,
			&i.Price,
			&i.Cash,
			&i.Items,
			&i.SourceAccountID,
			&i.Connector,
			&i.SourceLabel,
			&i.AccountID,
			&i.SettlementAccountID,
			&i.MatchPostingAmount,
			&i.MatchPostingCurrency,
			&i.MatchRowAmount,
			&i.MatchRowCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, book_id, priority, pattern, source_account_id, account_id, created_by, created_at FROM import_rules WHERE book_id = $1 ORDER BY priority, id
`

func (q *Queries) ListRules(ctx context.Context, bookID int64) ([]ImportRule, error) {
	rows, err := q.db.Query(ctx, listRules, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportRule{}
	for rows.Next() {
		var i ImportRule
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Priority,
			&i.Pattern,
			&i.SourceAccountID,
			&i.AccountID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceAccounts = `-- name: ListSourceAccounts :many
SELECT s.id, s.book_id, s.connector, s.external_id, s.label, s.currency, s.account_id, s.created_at, s.kind, s.settlement_account_id, s.ignored,
       (SELECT count(*) FROM import_rows r WHERE r.source_account_id = s.id AND r.status = 'pending')::BIGINT AS pending
FROM source_accounts s WHERE s.book_id = $1
ORDER BY s.connector, s.label, s.id
`

type ListSourceAccountsRow struct {
	ID                  int64
	BookID              int64
	Connector           string
	ExternalID          string
	Label               string
	Currency            *string
	AccountID           *int64
	CreatedAt           time.Time
	Kind                string
	SettlementAccountID *int64
	Ignored             bool
	Pending             int64
}

// A stable order: a row must not jump away when it is mapped.
func (q *Queries) ListSourceAccounts(ctx context.Context, bookID int64) ([]ListSourceAccountsRow, error) {
	rows, err := q.db.Query(ctx, listSourceAccounts, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceAccountsRow{}
	for rows.Next() {
		var i ListSourceAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Connector,
			&i.ExternalID,
			&i.Label,
			&i.Currency,
			&i.AccountID,
			&i.CreatedAt,
			&i.Kind,
			&i.SettlementAccountID,
			&i.Ignored,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapSourceAccount = `-- name: MapSourceAccount :one
UPDATE source_accounts SET account_id = $1, settlement_account_id = $2,
    ignored = $3
WHERE book_id = $4 AND id = $5 RETURNING id, book_id, connector, external_id, label, currency, account_id, created_at, kind, settlement_account_id, ignored
`

type MapSourceAccountParams struct {
	AccountID           *int64
	SettlementAccountID *int64
	Ignored             bool
	BookID              int64
	ID                  int64
}

func (q *Queries) MapSourceAccount(ctx context.Context, arg MapSourceAccountParams) (SourceAccount, error) {
	row := q.db.QueryRow(ctx, mapSourceAccount,
		arg.AccountID,
		arg.SettlementAccountID,
		arg.Ignored,
		arg.BookID,
		arg.ID,
	)
	var i SourceAccount
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Connector,
		&i.ExternalID,
		&i.Label,
		&i.Currency,
		&i.AccountID,
		&i.CreatedAt,
		&i.Kind,
		&i.SettlementAccountID,
		&i.Ignored,
	)
	return i, err
}

const pendingInvoiceRows = `-- name: PendingInvoiceRows :many
SELECT id FROM import_rows WHERE book_id = $1 AND status = 'pending' AND kind = 'invoice' ORDER BY date, id LIMIT 500
`

func (q *Queries) PendingInvoiceRows(ctx context.Context, bookID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, pendingInvoiceRows, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingRowsOfAccount = `-- name: PendingRowsOfAccount :many
SELECT r.id FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
WHERE r.book_id = $1 AND r.status = 'pending' AND r.kind = 'transaction'
  AND s.account_id = $2 AND r.date BETWEEN $3 AND $4
ORDER BY r.date, r.id
`

type PendingRowsOfAccountParams struct {
	BookID    int64
	AccountID *int64
	FromDate  time.Time
	ToDate    time.Time
}

// Waiting transaction rows on a ledger account, near a date: matched again
// once a trade has booked the cash they may duplicate.
func (q *Queries) PendingRowsOfAccount(ctx context.Context, arg PendingRowsOfAccountParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, pendingRowsOfAccount,
		arg.BookID,
		arg.AccountID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingRowsOfSource = `-- name: PendingRowsOfSource :many
SELECT id FROM import_rows WHERE source_account_id = $1 AND status = 'pending' ORDER BY date, id
`

func (q *Queries) PendingRowsOfSource(ctx context.Context, sourceAccountID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, pendingRowsOfSource, sourceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rowsMatchingRow = `-- name: RowsMatchingRow :many
SELECT id FROM import_rows WHERE book_id = $1 AND status = 'pending' AND match_row_id = $2
`

type RowsMatchingRowParams struct {
	BookID int64
	RowID  *int64
}

// Waiting rows that point at a row: matched again once it is decided.
func (q *Queries) RowsMatchingRow(ctx context.Context, arg RowsMatchingRowParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, rowsMatchingRow, arg.BookID, arg.RowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBatchCounts = `-- name: SetBatchCounts :exec
UPDATE import_batches SET received = $1, duplicates = $2 WHERE id = $3
`

type SetBatchCountsParams struct {
	Received   int32
	Duplicates int32
	ID         int64
}

func (q *Queries) SetBatchCounts(ctx context.Context, arg SetBatchCountsParams) error {
	_, err := q.db.Exec(ctx, setBatchCounts, arg.Received, arg.Duplicates, arg.ID)
	return err
}

const setPostingStatus = `-- name: SetPostingStatus :exec
UPDATE postings SET status = $1, cleared_on = $2
WHERE transaction_id = $3 AND account_id = $4 AND status <> 'reconciled'
`

type SetPostingStatusParams struct {
	Status        PostingStatus
	ClearedOn     *time.Time
	TransactionID int64
	AccountID     int64
}

func (q *Queries) SetPostingStatus(ctx context.Context, arg SetPostingStatusParams) error {
	_, err := q.db.Exec(ctx, setPostingStatus,
		arg.Status,
		arg.ClearedOn,
		arg.TransactionID,
		arg.AccountID,
	)
	return err
}

const setRowItems = `-- name: SetRowItems :exec
UPDATE import_rows SET items = $1 WHERE book_id = $2 AND id = $3
`

type SetRowItemsParams struct {
	Items  []byte
	BookID int64
	ID     int64
}

func (q *Queries) SetRowItems(ctx context.Context, arg SetRowItemsParams) error {
	_, err := q.db.Exec(ctx, setRowItems, arg.Items, arg.BookID, arg.ID)
	return err
}

const setRowProposal = `-- name: SetRowProposal :exec
UPDATE import_rows SET proposal = $1, proposed_account_id = $2,
    match_transaction_id = $3, match_row_id = $4,
    rule_id = $5
WHERE id = $6
`

type SetRowProposalParams struct {
	Proposal           string
	ProposedAccountID  *int64
	MatchTransactionID *int64
	MatchRowID         *int64
	RuleID             *int64
	ID                 int64
}

func (q *Queries) SetRowProposal(ctx context.Context, arg SetRowProposalParams) error {
	_, err := q.db.Exec(ctx, setRowProposal,
		arg.Proposal,
		arg.ProposedAccountID,
		arg.MatchTransactionID,
		arg.MatchRowID,
		arg.RuleID,
		arg.ID,
	)
	return err
}

const setSourceSecurity = `-- name: SetSourceSecurity :exec
INSERT INTO source_securities (source_account_id, commodity, account_id)
VALUES ($1, $2, $3)
ON CONFLICT (source_account_id, commodity) DO UPDATE SET account_id = EXCLUDED.account_id
`

type SetSourceSecurityParams struct {
	SourceAccountID int64
	Commodity       string
	AccountID       int64
}

func (q *Queries) SetSourceSecurity(ctx context.Context, arg SetSourceSecurityParams) error {
	_, err := q.db.Exec(ctx, setSourceSecurity, arg.SourceAccountID, arg.Commodity, arg.AccountID)
	return err
}

const upsertAssertion = `-- name: UpsertAssertion :exec
INSERT INTO balance_assertions (book_id, account_id, date, amount, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, date, source) DO UPDATE SET amount = EXCLUDED.amount
`

type UpsertAssertionParams struct {
	BookID    int64
	AccountID int64
	Date      time.Time
	Amount    decimal.Decimal
	Source    string
}

func (q *Queries) UpsertAssertion(ctx context.Context, arg UpsertAssertionParams) error {
	_, err := q.db.Exec(ctx, upsertAssertion,
		arg.BookID,
		arg.AccountID,
		arg.Date,
		arg.Amount,
		arg.Source,
	)
	return err
}

const upsertSourceAccount = `-- name: UpsertSourceAccount :one
INSERT INTO source_accounts (book_id, connector, external_id, label, currency, kind)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (book_id, connector, external_id) DO UPDATE
    SET label = CASE WHEN EXCLUDED.label <> '' THEN EXCLUDED.label ELSE source_accounts.label END,
        currency = coalesce(source_accounts.currency, EXCLUDED.currency),
        kind = EXCLUDED.kind
RETURNING id, book_id, connector, external_id, label, currency, account_id, created_at, kind, settlement_account_id, ignored
`

type UpsertSourceAccountParams struct {
	BookID     int64
	Connector  string
	ExternalID string
	Label      string
	Currency   *string
	Kind       string
}

func (q *Queries) UpsertSourceAccount(ctx context.Context, arg UpsertSourceAccountParams) (SourceAccount, error) {
	row := q.db.QueryRow(ctx, upsertSourceAccount,
		arg.BookID,
		arg.Connector,
		arg.ExternalID,
		arg.Label,
		arg.Currency,
		arg.Kind,
	)
	var i SourceAccount
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Connector,
		&i.ExternalID,
		&i.Label,
		&i.Currency,
		&i.AccountID,
		&i.CreatedAt,
		&i.Kind,
		&i.SettlementAccountID,
		&i.Ignored,
	)
	return i, err
}
