// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const accountDrift = `-- name: AccountDrift :many
SELECT DISTINCT ON (ba.account_id)
       ba.account_id, ba.date, ba.amount AS asserted, ba.source,
       coalesce((SELECT sum(p.amount) FROM postings p JOIN transactions t ON t.id = p.transaction_id
                 WHERE p.account_id = ba.account_id AND t.date <= ba.date), 0)::numeric AS booked
FROM balance_assertions ba
WHERE ba.book_id = $1
ORDER BY ba.account_id, ba.date DESC, ba.created_at DESC
`

type AccountDriftRow struct {
	AccountID int64
	Date      time.Time
	Asserted  decimal.Decimal
	Source    string
	Booked    decimal.Decimal
}

// The newest assertion of each account against what the books say on that
// date (in the account's own commodity).
func (q *Queries) AccountDrift(ctx context.Context, bookID int64) ([]AccountDriftRow, error) {
	rows, err := q.db.Query(ctx, accountDrift, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountDriftRow{}
	for rows.Next() {
		var i AccountDriftRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Date,
			&i.Asserted,
			&i.Source,
			&i.Booked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batches (book_id, connector, label, created_by) VALUES ($1, $2, $3, $4)
RETURNING id, book_id, connector, label, received, duplicates, created_by, created_at
`

type CreateImportBatchParams struct {
	BookID    int64
	Connector string
	Label     string
	CreatedBy *int64
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch,
		arg.BookID,
		arg.Connector,
		arg.Label,
		arg.CreatedBy,
	)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Connector,
		&i.Label,
		&i.Received,
		&i.Duplicates,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createRule = `-- name: CreateRule :one
INSERT INTO import_rules (book_id, priority, pattern, source_account_id, account_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, book_id, priority, pattern, source_account_id, account_id, created_by, created_at
`

type CreateRuleParams struct {
	BookID          int64
	Priority        int32
	Pattern         string
	SourceAccountID *int64
	AccountID       int64
	CreatedBy       *int64
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (ImportRule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.BookID,
		arg.Priority,
		arg.Pattern,
		arg.SourceAccountID,
		arg.AccountID,
		arg.CreatedBy,
	)
	var i ImportRule
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Priority,
		&i.Pattern,
		&i.SourceAccountID,
		&i.AccountID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const decideRow = `-- name: DecideRow :execrows
UPDATE import_rows SET status = $1, transaction_id = $2,
    decided_by = $3, decided_at = now()
WHERE id = $4 AND status = 'pending'
`

type DecideRowParams struct {
	Status        string
	TransactionID *int64
	DecidedBy     *int64
	ID            int64
}

func (q *Queries) DecideRow(ctx context.Context, arg DecideRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideRow,
		arg.Status,
		arg.TransactionID,
		arg.DecidedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRule = `-- name: DeleteRule :execrows
DELETE FROM import_rules WHERE book_id = $1 AND id = $2
`

type DeleteRuleParams struct {
	BookID int64
	ID     int64
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRule, arg.BookID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findDuplicate = `-- name: FindDuplicate :one
SELECT t.id FROM postings p JOIN transactions t ON t.id = p.transaction_id
WHERE t.book_id = $1 AND p.account_id = $2 AND p.amount = $3
  AND t.date BETWEEN $4 AND $5
  AND NOT EXISTS (SELECT 1 FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
                  WHERE r.book_id = $1 AND r.status <> 'ignored' AND s.account_id = $2
                    AND (r.transaction_id = t.id OR r.match_transaction_id = t.id))
ORDER BY abs(t.date - $6::DATE), t.id
LIMIT 1
`

type FindDuplicateParams struct {
	BookID    int64
	AccountID int64
	Amount    decimal.Decimal
	FromDate  time.Time
	ToDate    time.Time
	OnDate    time.Time
}

// A transaction already in the books for this row: same account, same
// amount, within a few days, not already claimed by a row of this account
// (a typed-in transfer is claimed once from each side).
func (q *Queries) FindDuplicate(ctx context.Context, arg FindDuplicateParams) (int64, error) {
	row := q.db.QueryRow(ctx, findDuplicate,
		arg.BookID,
		arg.AccountID,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findEstimate = `-- name: FindEstimate :one
SELECT t.id FROM postings p JOIN transactions t ON t.id = p.transaction_id
WHERE t.book_id = $1 AND p.account_id = $2 AND p.status = 'uncleared'
  AND p.amount BETWEEN $3 AND $4
  AND t.date BETWEEN $5 AND $6
  AND (SELECT count(*) FROM postings x WHERE x.transaction_id = t.id) = 2
  AND NOT EXISTS (SELECT 1 FROM import_rows r WHERE r.book_id = $1 AND r.status = 'pending'
                  AND r.match_transaction_id = t.id)
ORDER BY abs(p.amount - $7::NUMERIC), abs(t.date - $8::DATE), t.id
LIMIT 1
`

type FindEstimateParams struct {
	BookID    int64
	AccountID int64
	Lo        decimal.Decimal
	Hi        decimal.Decimal
	FromDate  time.Time
	ToDate    time.Time
	Amount    decimal.Decimal
	OnDate    time.Time
}

// An uncleared entry this posted row settles: same account and sign, the
// amount within the tolerance, a few days either side (a card charge
// entered as an estimate, or a pending row accepted earlier).
func (q *Queries) FindEstimate(ctx context.Context, arg FindEstimateParams) (int64, error) {
	row := q.db.QueryRow(ctx, findEstimate,
		arg.BookID,
		arg.AccountID,
		arg.Lo,
		arg.Hi,
		arg.FromDate,
		arg.ToDate,
		arg.Amount,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findTransferPartner = `-- name: FindTransferPartner :one
SELECT r.id FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
WHERE r.book_id = $1 AND r.status = 'pending' AND r.kind = 'transaction' AND r.id <> $2
  AND s.account_id IS NOT NULL AND s.account_id <> $3
  AND r.currency = $4 AND r.amount + $5::NUMERIC = 0
  AND r.date BETWEEN $6 AND $7
  AND r.proposal IN ('new', 'transfer') AND (r.match_row_id IS NULL OR r.match_row_id = $2)
ORDER BY abs(r.date - $8::DATE), r.id
LIMIT 1
`

type FindTransferPartnerParams struct {
	BookID    int64
	RowID     int64
	AccountID *int64
	Currency  string
	Amount    decimal.Decimal
	FromDate  time.Time
	ToDate    time.Time
	OnDate    time.Time
}

// The other side of a transfer between two of the book's own accounts:
// another pending row, from another mapped account, the opposite amount in
// the same currency, a few days apart, not already paired.
func (q *Queries) FindTransferPartner(ctx context.Context, arg FindTransferPartnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, findTransferPartner,
		arg.BookID,
		arg.RowID,
		arg.AccountID,
		arg.Currency,
		arg.Amount,
		arg.FromDate,
		arg.ToDate,
		arg.OnDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getImportRow = `-- name: GetImportRow :one
SELECT r.id, r.book_id, r.batch_id, r.source_account_id, r.kind, r.external_id, r.date, r.amount, r.currency, r.description, r.counterparty, r.pending, r.raw, r.proposal, r.proposed_account_id, r.match_transaction_id, r.match_row_id, r.rule_id, r.status, r.transaction_id, r.decided_by, r.decided_at, r.created_at, s.account_id, s.connector
FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
WHERE r.book_id = $1 AND r.id = $2
`

type GetImportRowParams struct {
	BookID int64
	ID     int64
}

type GetImportRowRow struct {
	ID                 int64
	BookID             int64
	BatchID            int64
	SourceAccountID    int64
	Kind               string
	ExternalID         string
	Date               time.Time
	Amount             decimal.Decimal
	Currency           string
	Description        string
	Counterparty       string
	Pending            bool
	Raw                []byte
	Proposal           string
	ProposedAccountID  *int64
	MatchTransactionID *int64
	MatchRowID         *int64
	RuleID             *int64
	Status             string
	TransactionID      *int64
	DecidedBy          *int64
	DecidedAt          *time.Time
	CreatedAt          time.Time
	AccountID          *int64
	Connector          string
}

func (q *Queries) GetImportRow(ctx context.Context, arg GetImportRowParams) (GetImportRowRow, error) {
	row := q.db.QueryRow(ctx, getImportRow, arg.BookID, arg.ID)
	var i GetImportRowRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.BatchID,
		&i.SourceAccountID,
		&i.Kind,
		&i.ExternalID,
		&i.Date,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Counterparty,
		&i.Pending,
		&i.Raw,
		&i.Proposal,
		&i.ProposedAccountID,
		&i.MatchTransactionID,
		&i.MatchRowID,
		&i.RuleID,
		&i.Status,
		&i.TransactionID,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.AccountID,
		&i.Connector,
	)
	return i, err
}

const getSourceAccount = `-- name: GetSourceAccount :one
SELECT id, book_id, connector, external_id, label, currency, account_id, created_at FROM source_accounts WHERE book_id = $1 AND id = $2
`

type GetSourceAccountParams struct {
	BookID int64
	ID     int64
}

func (q *Queries) GetSourceAccount(ctx context.Context, arg GetSourceAccountParams) (SourceAccount, error) {
	row := q.db.QueryRow(ctx, getSourceAccount, arg.BookID, arg.ID)
	var i SourceAccount
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Connector,
		&i.ExternalID,
		&i.Label,
		&i.Currency,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}

const insertImportRow = `-- name: InsertImportRow :one
INSERT INTO import_rows (book_id, batch_id, source_account_id, kind, external_id, date, amount, currency,
                         description, counterparty, pending, raw)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12)
ON CONFLICT (book_id, external_id) DO NOTHING
RETURNING id
`

type InsertImportRowParams struct {
	BookID          int64
	BatchID         int64
	SourceAccountID int64
	Kind            string
	ExternalID      string
	Date            time.Time
	Amount          decimal.Decimal
	Currency        string
	Description     string
	Counterparty    string
	Pending         bool
	Raw             []byte
}

// Nothing on a row already staged (the same external id): that is what
// makes a re-sync harmless. The caller counts the missing RETURNING.
func (q *Queries) InsertImportRow(ctx context.Context, arg InsertImportRowParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertImportRow,
		arg.BookID,
		arg.BatchID,
		arg.SourceAccountID,
		arg.Kind,
		arg.ExternalID,
		arg.Date,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Counterparty,
		arg.Pending,
		arg.Raw,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listQueue = `-- name: ListQueue :many
SELECT r.id, r.kind, r.external_id, r.date, r.amount, r.currency, r.description, r.counterparty, r.pending,
       r.proposal, r.proposed_account_id, r.match_transaction_id, r.match_row_id, r.rule_id,
       s.id AS source_account_id, s.connector, s.label AS source_label, s.account_id
FROM import_rows r JOIN source_accounts s ON s.id = r.source_account_id
WHERE r.book_id = $1 AND r.status = 'pending'
ORDER BY r.date DESC, r.id DESC
LIMIT $2
`

type ListQueueParams struct {
	BookID int64
	Lim    int32
}

type ListQueueRow struct {
	ID                 int64
	Kind               string
	ExternalID         string
	Date               time.Time
	Amount             decimal.Decimal
	Currency           string
	Description        string
	Counterparty       string
	Pending            bool
	Proposal           string
	ProposedAccountID  *int64
	MatchTransactionID *int64
	MatchRowID         *int64
	RuleID             *int64
	SourceAccountID    int64
	Connector          string
	SourceLabel        string
	AccountID          *int64
}

// The review queue: pending rows with their source account's mapping.
func (q *Queries) ListQueue(ctx context.Context, arg ListQueueParams) ([]ListQueueRow, error) {
	rows, err := q.db.Query(ctx, listQueue, arg.BookID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueueRow{}
	for rows.Next() {
		var i ListQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ExternalID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Counterparty,
			&i.Pending,
			&i.Proposal,
			&i.ProposedAccountID,
			&i.MatchTransactionID,
			&i.MatchRowID,
			&i.RuleID,
			&i.SourceAccountID,
			&i.Connector,
			&i.SourceLabel,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, book_id, priority, pattern, source_account_id, account_id, created_by, created_at FROM import_rules WHERE book_id = $1 ORDER BY priority, id
`

func (q *Queries) ListRules(ctx context.Context, bookID int64) ([]ImportRule, error) {
	rows, err := q.db.Query(ctx, listRules, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportRule{}
	for rows.Next() {
		var i ImportRule
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Priority,
			&i.Pattern,
			&i.SourceAccountID,
			&i.AccountID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceAccounts = `-- name: ListSourceAccounts :many
SELECT s.id, s.book_id, s.connector, s.external_id, s.label, s.currency, s.account_id, s.created_at,
       (SELECT count(*) FROM import_rows r WHERE r.source_account_id = s.id AND r.status = 'pending')::BIGINT AS pending
FROM source_accounts s WHERE s.book_id = $1
ORDER BY s.connector, s.label, s.id
`

type ListSourceAccountsRow struct {
	ID         int64
	BookID     int64
	Connector  string
	ExternalID string
	Label      string
	Currency   *string
	AccountID  *int64
	CreatedAt  time.Time
	Pending    int64
}

// A stable order: a row must not jump away when it is mapped.
func (q *Queries) ListSourceAccounts(ctx context.Context, bookID int64) ([]ListSourceAccountsRow, error) {
	rows, err := q.db.Query(ctx, listSourceAccounts, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceAccountsRow{}
	for rows.Next() {
		var i ListSourceAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Connector,
			&i.ExternalID,
			&i.Label,
			&i.Currency,
			&i.AccountID,
			&i.CreatedAt,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapSourceAccount = `-- name: MapSourceAccount :one
UPDATE source_accounts SET account_id = $1 WHERE book_id = $2 AND id = $3 RETURNING id, book_id, connector, external_id, label, currency, account_id, created_at
`

type MapSourceAccountParams struct {
	AccountID *int64
	BookID    int64
	ID        int64
}

func (q *Queries) MapSourceAccount(ctx context.Context, arg MapSourceAccountParams) (SourceAccount, error) {
	row := q.db.QueryRow(ctx, mapSourceAccount, arg.AccountID, arg.BookID, arg.ID)
	var i SourceAccount
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Connector,
		&i.ExternalID,
		&i.Label,
		&i.Currency,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}

const pendingRowsOfSource = `-- name: PendingRowsOfSource :many
SELECT id FROM import_rows WHERE source_account_id = $1 AND status = 'pending' ORDER BY date, id
`

func (q *Queries) PendingRowsOfSource(ctx context.Context, sourceAccountID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, pendingRowsOfSource, sourceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBatchCounts = `-- name: SetBatchCounts :exec
UPDATE import_batches SET received = $1, duplicates = $2 WHERE id = $3
`

type SetBatchCountsParams struct {
	Received   int32
	Duplicates int32
	ID         int64
}

func (q *Queries) SetBatchCounts(ctx context.Context, arg SetBatchCountsParams) error {
	_, err := q.db.Exec(ctx, setBatchCounts, arg.Received, arg.Duplicates, arg.ID)
	return err
}

const setPostingStatus = `-- name: SetPostingStatus :exec
UPDATE postings SET status = $1, cleared_on = $2
WHERE transaction_id = $3 AND account_id = $4 AND status <> 'reconciled'
`

type SetPostingStatusParams struct {
	Status        PostingStatus
	ClearedOn     *time.Time
	TransactionID int64
	AccountID     int64
}

func (q *Queries) SetPostingStatus(ctx context.Context, arg SetPostingStatusParams) error {
	_, err := q.db.Exec(ctx, setPostingStatus,
		arg.Status,
		arg.ClearedOn,
		arg.TransactionID,
		arg.AccountID,
	)
	return err
}

const setRowProposal = `-- name: SetRowProposal :exec
UPDATE import_rows SET proposal = $1, proposed_account_id = $2,
    match_transaction_id = $3, match_row_id = $4,
    rule_id = $5
WHERE id = $6
`

type SetRowProposalParams struct {
	Proposal           string
	ProposedAccountID  *int64
	MatchTransactionID *int64
	MatchRowID         *int64
	RuleID             *int64
	ID                 int64
}

func (q *Queries) SetRowProposal(ctx context.Context, arg SetRowProposalParams) error {
	_, err := q.db.Exec(ctx, setRowProposal,
		arg.Proposal,
		arg.ProposedAccountID,
		arg.MatchTransactionID,
		arg.MatchRowID,
		arg.RuleID,
		arg.ID,
	)
	return err
}

const upsertAssertion = `-- name: UpsertAssertion :exec
INSERT INTO balance_assertions (book_id, account_id, date, amount, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, date, source) DO UPDATE SET amount = EXCLUDED.amount
`

type UpsertAssertionParams struct {
	BookID    int64
	AccountID int64
	Date      time.Time
	Amount    decimal.Decimal
	Source    string
}

func (q *Queries) UpsertAssertion(ctx context.Context, arg UpsertAssertionParams) error {
	_, err := q.db.Exec(ctx, upsertAssertion,
		arg.BookID,
		arg.AccountID,
		arg.Date,
		arg.Amount,
		arg.Source,
	)
	return err
}

const upsertSourceAccount = `-- name: UpsertSourceAccount :one
INSERT INTO source_accounts (book_id, connector, external_id, label, currency)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (book_id, connector, external_id) DO UPDATE
    SET label = CASE WHEN EXCLUDED.label <> '' THEN EXCLUDED.label ELSE source_accounts.label END,
        currency = coalesce(source_accounts.currency, EXCLUDED.currency)
RETURNING id, book_id, connector, external_id, label, currency, account_id, created_at
`

type UpsertSourceAccountParams struct {
	BookID     int64
	Connector  string
	ExternalID string
	Label      string
	Currency   *string
}

func (q *Queries) UpsertSourceAccount(ctx context.Context, arg UpsertSourceAccountParams) (SourceAccount, error) {
	row := q.db.QueryRow(ctx, upsertSourceAccount,
		arg.BookID,
		arg.Connector,
		arg.ExternalID,
		arg.Label,
		arg.Currency,
	)
	var i SourceAccount
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Connector,
		&i.ExternalID,
		&i.Label,
		&i.Currency,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}
