// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const insertTransactionItem = `-- name: InsertTransactionItem :exec
INSERT INTO transaction_items (book_id, transaction_id, position, description, quantity, unit_price, amount, account_id, source)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9)
`

type InsertTransactionItemParams struct {
	BookID        int64
	TransactionID int64
	Position      int16
	Description   string
	Quantity      decimal.NullDecimal
	UnitPrice     decimal.NullDecimal
	Amount        decimal.Decimal
	AccountID     *int64
	Source        string
}

func (q *Queries) InsertTransactionItem(ctx context.Context, arg InsertTransactionItemParams) error {
	_, err := q.db.Exec(ctx, insertTransactionItem,
		arg.BookID,
		arg.TransactionID,
		arg.Position,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.Amount,
		arg.AccountID,
		arg.Source,
	)
	return err
}

const listTransactionItems = `-- name: ListTransactionItems :many
SELECT id, book_id, transaction_id, position, description, quantity, unit_price, amount, account_id, source FROM transaction_items WHERE transaction_id = ANY($1::BIGINT[]) ORDER BY transaction_id, position
`

func (q *Queries) ListTransactionItems(ctx context.Context, transactionIds []int64) ([]TransactionItem, error) {
	rows, err := q.db.Query(ctx, listTransactionItems, transactionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionItem{}
	for rows.Next() {
		var i TransactionItem
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.TransactionID,
			&i.Position,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.Amount,
			&i.AccountID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
