// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package db

import (
	"context"
	"net/netip"
	"time"
)

const advanceTOTPStep = `-- name: AdvanceTOTPStep :execrows
UPDATE mfa_factors SET last_step = $1 WHERE id = $2 AND last_step < $1
`

type AdvanceTOTPStepParams struct {
	Step int64
	ID   int64
}

// Accept a TOTP step only if it is newer than the last one: replay-proof
// even when two requests race.
func (q *Queries) AdvanceTOTPStep(ctx context.Context, arg AdvanceTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceTOTPStep, arg.Step, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpChallengeAttempts = `-- name: BumpChallengeAttempts :one
UPDATE auth_challenges SET attempts = attempts + 1 WHERE id = $1 RETURNING attempts
`

func (q *Queries) BumpChallengeAttempts(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, bumpChallengeAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const confirmFactor = `-- name: ConfirmFactor :exec
UPDATE mfa_factors SET confirmed_at = now(), last_step = $1 WHERE id = $2
`

type ConfirmFactorParams struct {
	LastStep int64
	ID       int64
}

func (q *Queries) ConfirmFactor(ctx context.Context, arg ConfirmFactorParams) error {
	_, err := q.db.Exec(ctx, confirmFactor, arg.LastStep, arg.ID)
	return err
}

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO auth_challenges (user_id, kind, token_hash, client, payload, code_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, kind, token_hash, client, payload, code_hash, code_sent_at, attempts, expires_at, created_at
`

type CreateChallengeParams struct {
	UserID    *int64
	Kind      string
	TokenHash []byte
	Client    string
	Payload   []byte
	CodeHash  []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.Client,
		arg.Payload,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.Client,
		&i.Payload,
		&i.CodeHash,
		&i.CodeSentAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasskey = `-- name: CreatePasskey :one
INSERT INTO webauthn_credentials (user_id, credential_id, data, name)
VALUES ($1, $2, $3, $4)
RETURNING id, credential_id, data, name, created_at, last_used_at
`

type CreatePasskeyParams struct {
	UserID       int64
	CredentialID []byte
	Data         []byte
	Name         string
}

type CreatePasskeyRow struct {
	ID           int64
	CredentialID []byte
	Data         []byte
	Name         string
	CreatedAt    time.Time
	LastUsedAt   *time.Time
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (CreatePasskeyRow, error) {
	row := q.db.QueryRow(ctx, createPasskey,
		arg.UserID,
		arg.CredentialID,
		arg.Data,
		arg.Name,
	)
	var i CreatePasskeyRow
	err := row.Scan(
		&i.ID,
		&i.CredentialID,
		&i.Data,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO mfa_recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type CreateRecoveryCodeParams struct {
	UserID   int64
	CodeHash []byte
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const deleteChallenge = `-- name: DeleteChallenge :execrows
DELETE FROM auth_challenges WHERE id = $1
`

func (q *Queries) DeleteChallenge(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChallenge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredChallenges = `-- name: DeleteExpiredChallenges :execrows
DELETE FROM auth_challenges WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFactor = `-- name: DeleteFactor :execrows
DELETE FROM mfa_factors WHERE user_id = $1 AND kind = $2
`

type DeleteFactorParams struct {
	UserID int64
	Kind   string
}

func (q *Queries) DeleteFactor(ctx context.Context, arg DeleteFactorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFactor, arg.UserID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePasskey = `-- name: DeletePasskey :execrows
DELETE FROM webauthn_credentials WHERE id = $1 AND user_id = $2
`

type DeletePasskeyParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM mfa_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const enableEmailFactor = `-- name: EnableEmailFactor :exec
INSERT INTO mfa_factors (user_id, kind, confirmed_at) VALUES ($1, 'email', now())
ON CONFLICT (user_id, kind) DO UPDATE SET confirmed_at = now()
`

func (q *Queries) EnableEmailFactor(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, enableEmailFactor, userID)
	return err
}

const getChallenge = `-- name: GetChallenge :one
SELECT id, user_id, kind, token_hash, client, payload, code_hash, code_sent_at, attempts, expires_at, created_at FROM auth_challenges WHERE token_hash = $1 AND kind = $2 AND expires_at > now()
`

type GetChallengeParams struct {
	TokenHash []byte
	Kind      string
}

func (q *Queries) GetChallenge(ctx context.Context, arg GetChallengeParams) (AuthChallenge, error) {
	row := q.db.QueryRow(ctx, getChallenge, arg.TokenHash, arg.Kind)
	var i AuthChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.Client,
		&i.Payload,
		&i.CodeHash,
		&i.CodeSentAt,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFactor = `-- name: GetFactor :one
SELECT id, user_id, kind, secret_enc, last_step, confirmed_at, created_at FROM mfa_factors WHERE user_id = $1 AND kind = $2
`

type GetFactorParams struct {
	UserID int64
	Kind   string
}

func (q *Queries) GetFactor(ctx context.Context, arg GetFactorParams) (MfaFactor, error) {
	row := q.db.QueryRow(ctx, getFactor, arg.UserID, arg.Kind)
	var i MfaFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SecretEnc,
		&i.LastStep,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMFAState = `-- name: GetMFAState :one
SELECT
    EXISTS (SELECT 1 FROM mfa_factors f WHERE f.user_id = $1 AND f.kind = 'totp' AND f.confirmed_at IS NOT NULL)::BOOLEAN AS totp,
    EXISTS (SELECT 1 FROM mfa_factors f WHERE f.user_id = $1 AND f.kind = 'email' AND f.confirmed_at IS NOT NULL)::BOOLEAN AS email,
    (SELECT count(*) FROM webauthn_credentials w WHERE w.user_id = $1)::BIGINT AS passkeys,
    (SELECT count(*) FROM mfa_recovery_codes r WHERE r.user_id = $1 AND r.used_at IS NULL)::BIGINT AS recovery_left
`

type GetMFAStateRow struct {
	Totp         bool
	Email        bool
	Passkeys     int64
	RecoveryLeft int64
}

// What a user has enrolled, for the login step and the gate.
func (q *Queries) GetMFAState(ctx context.Context, userID int64) (GetMFAStateRow, error) {
	row := q.db.QueryRow(ctx, getMFAState, userID)
	var i GetMFAStateRow
	err := row.Scan(
		&i.Totp,
		&i.Email,
		&i.Passkeys,
		&i.RecoveryLeft,
	)
	return i, err
}

const getPasskeyByCredentialID = `-- name: GetPasskeyByCredentialID :one
SELECT id, user_id, credential_id, data, name, created_at, last_used_at FROM webauthn_credentials WHERE credential_id = $1
`

func (q *Queries) GetPasskeyByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getPasskeyByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.Data,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUserByWebAuthnID = `-- name: GetUserByWebAuthnID :one
SELECT id, username, email, password_hash, display_name, is_admin, is_active, language, display_currency, timezone, date_format, theme, default_book_id, last_login_at, created_at, updated_at, email_verified_at, initialized_at, password_must_change, invited_by, webauthn_id, signin_alerts FROM users WHERE webauthn_id = $1
`

func (q *Queries) GetUserByWebAuthnID(ctx context.Context, webauthnID []byte) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWebAuthnID, webauthnID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.Language,
		&i.DisplayCurrency,
		&i.Timezone,
		&i.DateFormat,
		&i.Theme,
		&i.DefaultBookID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.InitializedAt,
		&i.PasswordMustChange,
		&i.InvitedBy,
		&i.WebauthnID,
		&i.SigninAlerts,
	)
	return i, err
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT id, credential_id, data, name, created_at, last_used_at FROM webauthn_credentials
WHERE user_id = $1 ORDER BY created_at
`

type ListPasskeysRow struct {
	ID           int64
	CredentialID []byte
	Data         []byte
	Name         string
	CreatedAt    time.Time
	LastUsedAt   *time.Time
}

func (q *Queries) ListPasskeys(ctx context.Context, userID int64) ([]ListPasskeysRow, error) {
	rows, err := q.db.Query(ctx, listPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPasskeysRow{}
	for rows.Next() {
		var i ListPasskeysRow
		if err := rows.Scan(
			&i.ID,
			&i.CredentialID,
			&i.Data,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetMFA = `-- name: ResetMFA :exec
WITH f AS (DELETE FROM mfa_factors WHERE mfa_factors.user_id = $1),
     w AS (DELETE FROM webauthn_credentials WHERE webauthn_credentials.user_id = $1)
DELETE FROM mfa_recovery_codes WHERE mfa_recovery_codes.user_id = $1
`

// Break-glass: every factor, passkey and recovery code of a user.
func (q *Queries) ResetMFA(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, resetMFA, userID)
	return err
}

const seenFromIP = `-- name: SeenFromIP :one
SELECT EXISTS (
    SELECT 1 FROM auth_events
    WHERE user_id = $1 AND ip = $2::inet
      AND event = 'signed_in'
      AND created_at > now() - INTERVAL '90 days'
)::BOOLEAN
`

type SeenFromIPParams struct {
	UserID *int64
	Ip     *netip.Addr
}

// Whether this user signed in successfully from ip in the last 90 days (the
// new-sign-in alert stays quiet then).
func (q *Queries) SeenFromIP(ctx context.Context, arg SeenFromIPParams) (bool, error) {
	row := q.db.QueryRow(ctx, seenFromIP, arg.UserID, arg.Ip)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setChallengeCode = `-- name: SetChallengeCode :exec
UPDATE auth_challenges SET code_hash = $1, code_sent_at = now(), attempts = 0 WHERE id = $2
`

type SetChallengeCodeParams struct {
	CodeHash []byte
	ID       int64
}

func (q *Queries) SetChallengeCode(ctx context.Context, arg SetChallengeCodeParams) error {
	_, err := q.db.Exec(ctx, setChallengeCode, arg.CodeHash, arg.ID)
	return err
}

const setSignInAlerts = `-- name: SetSignInAlerts :exec
UPDATE users SET signin_alerts = $1 WHERE id = $2
`

type SetSignInAlertsParams struct {
	SigninAlerts bool
	ID           int64
}

func (q *Queries) SetSignInAlerts(ctx context.Context, arg SetSignInAlertsParams) error {
	_, err := q.db.Exec(ctx, setSignInAlerts, arg.SigninAlerts, arg.ID)
	return err
}

const setWebAuthnID = `-- name: SetWebAuthnID :one
UPDATE users SET webauthn_id = coalesce(webauthn_id, $1) WHERE id = $2 RETURNING webauthn_id
`

type SetWebAuthnIDParams struct {
	WebauthnID []byte
	ID         int64
}

func (q *Queries) SetWebAuthnID(ctx context.Context, arg SetWebAuthnIDParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, setWebAuthnID, arg.WebauthnID, arg.ID)
	var webauthn_id []byte
	err := row.Scan(&webauthn_id)
	return webauthn_id, err
}

const touchPasskey = `-- name: TouchPasskey :exec
UPDATE webauthn_credentials SET data = $1, last_used_at = now() WHERE id = $2
`

type TouchPasskeyParams struct {
	Data []byte
	ID   int64
}

func (q *Queries) TouchPasskey(ctx context.Context, arg TouchPasskeyParams) error {
	_, err := q.db.Exec(ctx, touchPasskey, arg.Data, arg.ID)
	return err
}

const upsertPendingTOTP = `-- name: UpsertPendingTOTP :one
INSERT INTO mfa_factors (user_id, kind, secret_enc)
VALUES ($1, 'totp', $2)
ON CONFLICT (user_id, kind) DO UPDATE SET secret_enc = EXCLUDED.secret_enc, last_step = 0, created_at = now()
    WHERE mfa_factors.confirmed_at IS NULL
RETURNING id, user_id, kind, secret_enc, last_step, confirmed_at, created_at
`

type UpsertPendingTOTPParams struct {
	UserID    int64
	SecretEnc []byte
}

// A new (unconfirmed) TOTP seed; replaces an unfinished enrolment, never a
// confirmed one.
func (q *Queries) UpsertPendingTOTP(ctx context.Context, arg UpsertPendingTOTPParams) (MfaFactor, error) {
	row := q.db.QueryRow(ctx, upsertPendingTOTP, arg.UserID, arg.SecretEnc)
	var i MfaFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SecretEnc,
		&i.LastStep,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE mfa_recovery_codes SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	UserID   int64
	CodeHash []byte
}

func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
