// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/shopspring/decimal"
)

type AccountClass string

const (
	AccountClassAsset     AccountClass = "asset"
	AccountClassLiability AccountClass = "liability"
	AccountClassEquity    AccountClass = "equity"
	AccountClassIncome    AccountClass = "income"
	AccountClassExpense   AccountClass = "expense"
)

func (e *AccountClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountClass(s)
	case string:
		*e = AccountClass(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountClass: %T", src)
	}
	return nil
}

type NullAccountClass struct {
	AccountClass AccountClass
	Valid        bool // Valid is true if AccountClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountClass) Scan(value interface{}) error {
	if value == nil {
		ns.AccountClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountClass), nil
}

func (e AccountClass) Valid() bool {
	switch e {
	case AccountClassAsset,
		AccountClassLiability,
		AccountClassEquity,
		AccountClassIncome,
		AccountClassExpense:
		return true
	}
	return false
}

type CfClass string

const (
	CfClassOperating CfClass = "operating"
	CfClassInvesting CfClass = "investing"
	CfClassFinancing CfClass = "financing"
)

func (e *CfClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CfClass(s)
	case string:
		*e = CfClass(s)
	default:
		return fmt.Errorf("unsupported scan type for CfClass: %T", src)
	}
	return nil
}

type NullCfClass struct {
	CfClass CfClass
	Valid   bool // Valid is true if CfClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCfClass) Scan(value interface{}) error {
	if value == nil {
		ns.CfClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CfClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCfClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CfClass), nil
}

func (e CfClass) Valid() bool {
	switch e {
	case CfClassOperating,
		CfClassInvesting,
		CfClassFinancing:
		return true
	}
	return false
}

type CommodityKind string

const (
	CommodityKindCurrency CommodityKind = "currency"
	CommodityKindSecurity CommodityKind = "security"
	CommodityKindPoints   CommodityKind = "points"
)

func (e *CommodityKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommodityKind(s)
	case string:
		*e = CommodityKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CommodityKind: %T", src)
	}
	return nil
}

type NullCommodityKind struct {
	CommodityKind CommodityKind
	Valid         bool // Valid is true if CommodityKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommodityKind) Scan(value interface{}) error {
	if value == nil {
		ns.CommodityKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommodityKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommodityKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommodityKind), nil
}

func (e CommodityKind) Valid() bool {
	switch e {
	case CommodityKindCurrency,
		CommodityKindSecurity,
		CommodityKindPoints:
		return true
	}
	return false
}

type MemberRole string

const (
	MemberRoleViewer MemberRole = "viewer"
	MemberRoleEditor MemberRole = "editor"
	MemberRoleOwner  MemberRole = "owner"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

func (e MemberRole) Valid() bool {
	switch e {
	case MemberRoleViewer,
		MemberRoleEditor,
		MemberRoleOwner:
		return true
	}
	return false
}

type PostingStatus string

const (
	PostingStatusUncleared  PostingStatus = "uncleared"
	PostingStatusCleared    PostingStatus = "cleared"
	PostingStatusReconciled PostingStatus = "reconciled"
)

func (e *PostingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostingStatus(s)
	case string:
		*e = PostingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostingStatus: %T", src)
	}
	return nil
}

type NullPostingStatus struct {
	PostingStatus PostingStatus
	Valid         bool // Valid is true if PostingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostingStatus), nil
}

func (e PostingStatus) Valid() bool {
	switch e {
	case PostingStatusUncleared,
		PostingStatusCleared,
		PostingStatusReconciled:
		return true
	}
	return false
}

type AccessRequest struct {
	ID        int64
	Username  string
	Email     string
	Message   string
	Ip        *netip.Addr
	Status    string
	DecidedBy *int64
	DecidedAt *time.Time
	CreatedAt time.Time
}

type Account struct {
	ID            int64
	BookID        int64
	ParentID      *int64
	Class         AccountClass
	Name          *string
	TemplateKey   *string
	Code          *string
	Commodity     *string
	IsCurrent     bool
	IsCash        bool
	CfClass       CfClass
	IsPlaceholder bool
	ArchivedAt    *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AuditLog struct {
	ID        int64
	BookID    *int64
	TableName string
	RowID     *int64
	Action    string
	OldValues []byte
	NewValues []byte
	ChangedBy *int64
	ChangedAt time.Time
}

type AuthChallenge struct {
	ID         int64
	UserID     *int64
	Kind       string
	TokenHash  []byte
	Client     string
	Payload    []byte
	CodeHash   []byte
	CodeSentAt *time.Time
	Attempts   int32
	ExpiresAt  time.Time
	CreatedAt  time.Time
}

type AuthEvent struct {
	ID        int64
	Username  string
	UserID    *int64
	Ip        *netip.Addr
	UserAgent string
	Event     string
	Failure   bool
	Detail    []byte
	CreatedAt time.Time
}

type Book struct {
	ID                      int64
	Name                    string
	BaseCurrency            string
	LockDate                *time.Time
	InterestDividendCfClass CfClass
	CreatedBy               *int64
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type BookMember struct {
	BookID    int64
	UserID    int64
	Role      MemberRole
	CreatedAt time.Time
}

type Commodity struct {
	Code          string
	Kind          CommodityKind
	Name          string
	Decimals      int16
	QuoteCurrency *string
	ExchangeMic   *string
	ContractSize  decimal.NullDecimal
}

type EmailToken struct {
	ID        int64
	UserID    *int64
	Kind      string
	Email     string
	TokenHash []byte
	CodeHash  []byte
	Payload   []byte
	Attempts  int32
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedBy *int64
	CreatedAt time.Time
}

type MfaFactor struct {
	ID          int64
	UserID      int64
	Kind        string
	SecretEnc   []byte
	LastStep    int64
	ConfirmedAt *time.Time
	CreatedAt   time.Time
}

type MfaRecoveryCode struct {
	ID        int64
	UserID    int64
	CodeHash  []byte
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Posting struct {
	ID            int64
	TransactionID int64
	AccountID     int64
	Position      int16
	Commodity     string
	Amount        decimal.Decimal
	BaseAmount    decimal.Decimal
	UnitCost      decimal.NullDecimal
	Status        PostingStatus
	ClearedOn     *time.Time
	Memo          string
}

type Price struct {
	ID        int64
	Commodity string
	Quote     string
	Date      time.Time
	Rate      decimal.Decimal
	Source    string
	CreatedBy *int64
	CreatedAt time.Time
}

type Session struct {
	ID         int64
	UserID     int64
	TokenHash  []byte
	Kind       string
	Label      string
	UserAgent  string
	CreatedAt  time.Time
	LastUsedAt time.Time
	ExpiresAt  time.Time
	Ip         *netip.Addr
	Aal        int16
}

type SystemSetting struct {
	ID                     bool
	Registration           string
	MfaRequired            bool
	MfaMethods             []string
	DefaultLanguage        string
	DefaultDisplayCurrency string
	DefaultTimezone        string
	DefaultDateFormat      string
	DefaultTheme           string
	SessionTtlSeconds      *int64
	InviteTtlSeconds       int64
	LoginMaxFailures       int32
	LoginIpMaxFailures     int32
	LoginUserMaxFailures   int32
	LoginWindowSeconds     int64
	MailConfigured         bool
	MailDriver             string
	SmtpHost               string
	SmtpPort               int32
	SmtpSecurity           string
	SmtpUser               string
	SmtpPassEnc            []byte
	MailFrom               string
	MailFromName           string
	UpdatedBy              *int64
	UpdatedAt              time.Time
}

type Tag struct {
	ID     int64
	BookID int64
	Name   string
}

type Transaction struct {
	ID         int64
	BookID     int64
	Date       time.Time
	Payee      string
	Memo       string
	Source     string
	ExternalID *string
	CreatedBy  *int64
	UpdatedBy  *int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TransactionTag struct {
	TransactionID int64
	TagID         int64
}

type User struct {
	ID                 int64
	Username           string
	Email              string
	PasswordHash       string
	DisplayName        string
	IsAdmin            bool
	IsActive           bool
	Language           string
	DisplayCurrency    string
	Timezone           string
	DateFormat         string
	Theme              string
	DefaultBookID      *int64
	LastLoginAt        *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailVerifiedAt    *time.Time
	InitializedAt      *time.Time
	PasswordMustChange bool
	InvitedBy          *int64
	WebauthnID         []byte
	SigninAlerts       bool
}

type WebauthnCredential struct {
	ID           int64
	UserID       int64
	CredentialID []byte
	Data         []byte
	Name         string
	CreatedAt    time.Time
	LastUsedAt   *time.Time
}
