// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prices.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const deletePrice = `-- name: DeletePrice :execrows
DELETE FROM prices WHERE id = $1 AND source = 'manual'
`

func (q *Queries) DeletePrice(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePrice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestPrice = `-- name: LatestPrice :one
SELECT id, commodity, quote, date, rate, source, created_by, created_at FROM prices
WHERE commodity = $1 AND quote = $2 AND date <= $3
ORDER BY date DESC, (source = 'manual') DESC
LIMIT 1
`

type LatestPriceParams struct {
	Commodity string
	Quote     string
	OnDate    time.Time
}

// The newest rate on or before the date; on the same day a manual rate wins.
func (q *Queries) LatestPrice(ctx context.Context, arg LatestPriceParams) (Price, error) {
	row := q.db.QueryRow(ctx, latestPrice, arg.Commodity, arg.Quote, arg.OnDate)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.Commodity,
		&i.Quote,
		&i.Date,
		&i.Rate,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPrices = `-- name: ListPrices :many
SELECT id, commodity, quote, date, rate, source, created_by, created_at FROM prices
WHERE ($1::text IS NULL OR commodity = $1::text OR quote = $1::text)
ORDER BY date DESC, commodity, quote
LIMIT $2
`

type ListPricesParams struct {
	Commodity *string
	Lim       int32
}

func (q *Queries) ListPrices(ctx context.Context, arg ListPricesParams) ([]Price, error) {
	rows, err := q.db.Query(ctx, listPrices, arg.Commodity, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Price{}
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.Commodity,
			&i.Quote,
			&i.Date,
			&i.Rate,
			&i.Source,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPrice = `-- name: UpsertPrice :one
INSERT INTO prices (commodity, quote, date, rate, source, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (commodity, quote, date, source) DO UPDATE SET rate = EXCLUDED.rate, created_by = EXCLUDED.created_by
RETURNING id, commodity, quote, date, rate, source, created_by, created_at
`

type UpsertPriceParams struct {
	Commodity string
	Quote     string
	Date      time.Time
	Rate      decimal.Decimal
	Source    string
	CreatedBy *int64
}

func (q *Queries) UpsertPrice(ctx context.Context, arg UpsertPriceParams) (Price, error) {
	row := q.db.QueryRow(ctx, upsertPrice,
		arg.Commodity,
		arg.Quote,
		arg.Date,
		arg.Rate,
		arg.Source,
		arg.CreatedBy,
	)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.Commodity,
		&i.Quote,
		&i.Date,
		&i.Rate,
		&i.Source,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
