// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rates.sql

package db

import (
	"context"
	"time"
)

const bookCurrencies = `-- name: BookCurrencies :many
SELECT DISTINCT code FROM (
    SELECT b.base_currency AS code FROM books b WHERE b.id = $1
    UNION SELECT a.commodity FROM accounts a
        JOIN commodities c ON c.code = a.commodity
        WHERE a.book_id = $1 AND c.kind = 'currency'
    UNION SELECT u.display_currency FROM book_members m JOIN users u ON u.id = m.user_id WHERE m.book_id = $1
) x WHERE code IS NOT NULL ORDER BY code
`

// The currencies a book holds or reports in: its base, its accounts', and
// its members' display currencies.
func (q *Queries) BookCurrencies(ctx context.Context, bookID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, bookCurrencies, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failedTodayFor = `-- name: FailedTodayFor :one
SELECT count(*) FROM rate_fetches
WHERE error <> '' AND requested = $1 AND fetched_at > date_trunc('day', now())
`

// Failed attempts for a requested day since midnight UTC: the backfill
// gives up on a day after three.
func (q *Queries) FailedTodayFor(ctx context.Context, day *time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, failedTodayFor, day)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fetchedDays = `-- name: FetchedDays :many
SELECT DISTINCT rate_date::DATE AS day FROM rate_fetches
WHERE error = '' AND rate_date BETWEEN $1 AND $2
`

type FetchedDaysParams struct {
	FromDate *time.Time
	ToDate   *time.Time
}

// Days in [from, to] that already have a successful fetch.
func (q *Queries) FetchedDays(ctx context.Context, arg FetchedDaysParams) ([]time.Time, error) {
	rows, err := q.db.Query(ctx, fetchedDays, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var day time.Time
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastSuccessfulFetch = `-- name: LastSuccessfulFetch :one
SELECT id, source, rate_date, requested, rates, skipped, error, fetched_at FROM rate_fetches WHERE error = '' ORDER BY fetched_at DESC LIMIT 1
`

func (q *Queries) LastSuccessfulFetch(ctx context.Context) (RateFetch, error) {
	row := q.db.QueryRow(ctx, lastSuccessfulFetch)
	var i RateFetch
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.RateDate,
		&i.Requested,
		&i.Rates,
		&i.Skipped,
		&i.Error,
		&i.FetchedAt,
	)
	return i, err
}

const listRateFetches = `-- name: ListRateFetches :many
SELECT id, source, rate_date, requested, rates, skipped, error, fetched_at FROM rate_fetches ORDER BY fetched_at DESC LIMIT $1
`

func (q *Queries) ListRateFetches(ctx context.Context, lim int32) ([]RateFetch, error) {
	rows, err := q.db.Query(ctx, listRateFetches, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RateFetch{}
	for rows.Next() {
		var i RateFetch
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.RateDate,
			&i.Requested,
			&i.Rates,
			&i.Skipped,
			&i.Error,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRateFetch = `-- name: RecordRateFetch :one
INSERT INTO rate_fetches (source, rate_date, requested, rates, skipped, error)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, source, rate_date, requested, rates, skipped, error, fetched_at
`

type RecordRateFetchParams struct {
	Source    string
	RateDate  *time.Time
	Requested *time.Time
	Rates     int32
	Skipped   int32
	Error     string
}

func (q *Queries) RecordRateFetch(ctx context.Context, arg RecordRateFetchParams) (RateFetch, error) {
	row := q.db.QueryRow(ctx, recordRateFetch,
		arg.Source,
		arg.RateDate,
		arg.Requested,
		arg.Rates,
		arg.Skipped,
		arg.Error,
	)
	var i RateFetch
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.RateDate,
		&i.Requested,
		&i.Rates,
		&i.Skipped,
		&i.Error,
		&i.FetchedAt,
	)
	return i, err
}
