// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package db

import (
	"context"
)

const clearSMTPPassword = `-- name: ClearSMTPPassword :exec
UPDATE system_settings SET smtp_pass_enc = NULL WHERE id
`

func (q *Queries) ClearSMTPPassword(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearSMTPPassword)
	return err
}

const getSystemSettings = `-- name: GetSystemSettings :one
SELECT id, registration, mfa_required, mfa_methods, default_language, default_display_currency, default_timezone, default_date_format, default_theme, session_ttl_seconds, invite_ttl_seconds, login_max_failures, login_ip_max_failures, login_user_max_failures, login_window_seconds, mail_configured, mail_driver, smtp_host, smtp_port, smtp_security, smtp_user, smtp_pass_enc, mail_from, mail_from_name, updated_by, updated_at FROM system_settings WHERE id
`

func (q *Queries) GetSystemSettings(ctx context.Context) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSettings)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.Registration,
		&i.MfaRequired,
		&i.MfaMethods,
		&i.DefaultLanguage,
		&i.DefaultDisplayCurrency,
		&i.DefaultTimezone,
		&i.DefaultDateFormat,
		&i.DefaultTheme,
		&i.SessionTtlSeconds,
		&i.InviteTtlSeconds,
		&i.LoginMaxFailures,
		&i.LoginIpMaxFailures,
		&i.LoginUserMaxFailures,
		&i.LoginWindowSeconds,
		&i.MailConfigured,
		&i.MailDriver,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpSecurity,
		&i.SmtpUser,
		&i.SmtpPassEnc,
		&i.MailFrom,
		&i.MailFromName,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMailSettings = `-- name: UpdateMailSettings :one
UPDATE system_settings SET
    mail_configured = true,
    mail_driver     = $1,
    smtp_host       = $2,
    smtp_port       = $3,
    smtp_security   = $4,
    smtp_user       = $5,
    smtp_pass_enc   = coalesce($6, smtp_pass_enc),
    mail_from       = $7,
    mail_from_name  = $8,
    updated_by      = $9
WHERE id
RETURNING id, registration, mfa_required, mfa_methods, default_language, default_display_currency, default_timezone, default_date_format, default_theme, session_ttl_seconds, invite_ttl_seconds, login_max_failures, login_ip_max_failures, login_user_max_failures, login_window_seconds, mail_configured, mail_driver, smtp_host, smtp_port, smtp_security, smtp_user, smtp_pass_enc, mail_from, mail_from_name, updated_by, updated_at
`

type UpdateMailSettingsParams struct {
	MailDriver   string
	SmtpHost     string
	SmtpPort     int32
	SmtpSecurity string
	SmtpUser     string
	SmtpPassEnc  []byte
	MailFrom     string
	MailFromName string
	UpdatedBy    *int64
}

// smtp_pass_enc is kept when the new value is NULL: the API never returns
// the password, so an unchanged form sends none.
func (q *Queries) UpdateMailSettings(ctx context.Context, arg UpdateMailSettingsParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, updateMailSettings,
		arg.MailDriver,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpSecurity,
		arg.SmtpUser,
		arg.SmtpPassEnc,
		arg.MailFrom,
		arg.MailFromName,
		arg.UpdatedBy,
	)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.Registration,
		&i.MfaRequired,
		&i.MfaMethods,
		&i.DefaultLanguage,
		&i.DefaultDisplayCurrency,
		&i.DefaultTimezone,
		&i.DefaultDateFormat,
		&i.DefaultTheme,
		&i.SessionTtlSeconds,
		&i.InviteTtlSeconds,
		&i.LoginMaxFailures,
		&i.LoginIpMaxFailures,
		&i.LoginUserMaxFailures,
		&i.LoginWindowSeconds,
		&i.MailConfigured,
		&i.MailDriver,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpSecurity,
		&i.SmtpUser,
		&i.SmtpPassEnc,
		&i.MailFrom,
		&i.MailFromName,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSystemSettings = `-- name: UpdateSystemSettings :one
UPDATE system_settings SET
    registration             = $1,
    mfa_required             = $2,
    mfa_methods              = $3,
    default_language         = $4,
    default_display_currency = $5,
    default_timezone         = $6,
    default_date_format      = $7,
    default_theme            = $8,
    session_ttl_seconds      = $9,
    invite_ttl_seconds       = $10,
    login_max_failures       = $11,
    login_ip_max_failures    = $12,
    login_user_max_failures  = $13,
    login_window_seconds     = $14,
    updated_by               = $15
WHERE id
RETURNING id, registration, mfa_required, mfa_methods, default_language, default_display_currency, default_timezone, default_date_format, default_theme, session_ttl_seconds, invite_ttl_seconds, login_max_failures, login_ip_max_failures, login_user_max_failures, login_window_seconds, mail_configured, mail_driver, smtp_host, smtp_port, smtp_security, smtp_user, smtp_pass_enc, mail_from, mail_from_name, updated_by, updated_at
`

type UpdateSystemSettingsParams struct {
	Registration           string
	MfaRequired            bool
	MfaMethods             []string
	DefaultLanguage        string
	DefaultDisplayCurrency string
	DefaultTimezone        string
	DefaultDateFormat      string
	DefaultTheme           string
	SessionTtlSeconds      *int64
	InviteTtlSeconds       int64
	LoginMaxFailures       int32
	LoginIpMaxFailures     int32
	LoginUserMaxFailures   int32
	LoginWindowSeconds     int64
	UpdatedBy              *int64
}

func (q *Queries) UpdateSystemSettings(ctx context.Context, arg UpdateSystemSettingsParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, updateSystemSettings,
		arg.Registration,
		arg.MfaRequired,
		arg.MfaMethods,
		arg.DefaultLanguage,
		arg.DefaultDisplayCurrency,
		arg.DefaultTimezone,
		arg.DefaultDateFormat,
		arg.DefaultTheme,
		arg.SessionTtlSeconds,
		arg.InviteTtlSeconds,
		arg.LoginMaxFailures,
		arg.LoginIpMaxFailures,
		arg.LoginUserMaxFailures,
		arg.LoginWindowSeconds,
		arg.UpdatedBy,
	)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.Registration,
		&i.MfaRequired,
		&i.MfaMethods,
		&i.DefaultLanguage,
		&i.DefaultDisplayCurrency,
		&i.DefaultTimezone,
		&i.DefaultDateFormat,
		&i.DefaultTheme,
		&i.SessionTtlSeconds,
		&i.InviteTtlSeconds,
		&i.LoginMaxFailures,
		&i.LoginIpMaxFailures,
		&i.LoginUserMaxFailures,
		&i.LoginWindowSeconds,
		&i.MailConfigured,
		&i.MailDriver,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpSecurity,
		&i.SmtpUser,
		&i.SmtpPassEnc,
		&i.MailFrom,
		&i.MailFromName,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
