// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const addTransactionTag = `-- name: AddTransactionTag :exec
INSERT INTO transaction_tags (transaction_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddTransactionTagParams struct {
	TransactionID int64
	TagID         int64
}

func (q *Queries) AddTransactionTag(ctx context.Context, arg AddTransactionTagParams) error {
	_, err := q.db.Exec(ctx, addTransactionTag, arg.TransactionID, arg.TagID)
	return err
}

const clearTransactionTags = `-- name: ClearTransactionTags :exec
DELETE FROM transaction_tags WHERE transaction_id = $1
`

func (q *Queries) ClearTransactionTags(ctx context.Context, transactionID int64) error {
	_, err := q.db.Exec(ctx, clearTransactionTags, transactionID)
	return err
}

const createPosting = `-- name: CreatePosting :one
INSERT INTO postings (transaction_id, account_id, position, commodity, amount, base_amount,
                      unit_cost, status, cleared_on, memo)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10)
RETURNING id, transaction_id, account_id, position, commodity, amount, base_amount, unit_cost, status, cleared_on, memo
`

type CreatePostingParams struct {
	TransactionID int64
	AccountID     int64
	Position      int16
	Commodity     string
	Amount        decimal.Decimal
	BaseAmount    decimal.Decimal
	UnitCost      decimal.NullDecimal
	Status        PostingStatus
	ClearedOn     *time.Time
	Memo          string
}

func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) (Posting, error) {
	row := q.db.QueryRow(ctx, createPosting,
		arg.TransactionID,
		arg.AccountID,
		arg.Position,
		arg.Commodity,
		arg.Amount,
		arg.BaseAmount,
		arg.UnitCost,
		arg.Status,
		arg.ClearedOn,
		arg.Memo,
	)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Position,
		&i.Commodity,
		&i.Amount,
		&i.BaseAmount,
		&i.UnitCost,
		&i.Status,
		&i.ClearedOn,
		&i.Memo,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (book_id, date, payee, memo, source, external_id, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, book_id, date, payee, memo, source, external_id, created_by, updated_by, created_at, updated_at
`

type CreateTransactionParams struct {
	BookID     int64
	Date       time.Time
	Payee      string
	Memo       string
	Source     string
	ExternalID *string
	UserID     *int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.BookID,
		arg.Date,
		arg.Payee,
		arg.Memo,
		arg.Source,
		arg.ExternalID,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Date,
		&i.Payee,
		&i.Memo,
		&i.Source,
		&i.ExternalID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePostings = `-- name: DeletePostings :exec
DELETE FROM postings WHERE transaction_id = $1
`

func (q *Queries) DeletePostings(ctx context.Context, transactionID int64) error {
	_, err := q.db.Exec(ctx, deletePostings, transactionID)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE book_id = $1 AND id = $2
`

type DeleteTransactionParams struct {
	BookID int64
	ID     int64
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.BookID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, book_id, date, payee, memo, source, external_id, created_by, updated_by, created_at, updated_at FROM transactions WHERE book_id = $1 AND id = $2
`

type GetTransactionParams struct {
	BookID int64
	ID     int64
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.BookID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Date,
		&i.Payee,
		&i.Memo,
		&i.Source,
		&i.ExternalID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPostings = `-- name: ListPostings :many
SELECT id, transaction_id, account_id, position, commodity, amount, base_amount, unit_cost, status, cleared_on, memo FROM postings WHERE transaction_id = ANY($1::bigint[])
ORDER BY transaction_id, position, id
`

func (q *Queries) ListPostings(ctx context.Context, transactionIds []int64) ([]Posting, error) {
	rows, err := q.db.Query(ctx, listPostings, transactionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Posting{}
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Position,
			&i.Commodity,
			&i.Amount,
			&i.BaseAmount,
			&i.UnitCost,
			&i.Status,
			&i.ClearedOn,
			&i.Memo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, book_id, name FROM tags WHERE book_id = $1 ORDER BY lower(name)
`

func (q *Queries) ListTags(ctx context.Context, bookID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.BookID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionTags = `-- name: ListTransactionTags :many
SELECT tt.transaction_id, t.name
FROM transaction_tags tt
JOIN tags t ON t.id = tt.tag_id
WHERE tt.transaction_id = ANY($1::bigint[])
ORDER BY lower(t.name)
`

type ListTransactionTagsRow struct {
	TransactionID int64
	Name          string
}

func (q *Queries) ListTransactionTags(ctx context.Context, transactionIds []int64) ([]ListTransactionTagsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionTags, transactionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionTagsRow{}
	for rows.Next() {
		var i ListTransactionTagsRow
		if err := rows.Scan(&i.TransactionID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.book_id, t.date, t.payee, t.memo, t.source, t.external_id, t.created_by, t.updated_by, t.created_at, t.updated_at
FROM transactions t
WHERE t.book_id = $1
  AND ($2::date IS NULL OR t.date >= $2::date)
  AND ($3::date IS NULL OR t.date <= $3::date)
  AND (cardinality($4::bigint[]) = 0 OR EXISTS (
        SELECT 1 FROM postings p WHERE p.transaction_id = t.id AND p.account_id = ANY($4::bigint[])))
  AND ($5::text IS NULL
       OR t.payee ILIKE '%' || $5::text || '%'
       OR t.memo ILIKE '%' || $5::text || '%')
  AND ($6::bigint IS NULL OR EXISTS (
        SELECT 1 FROM transaction_tags tt WHERE tt.transaction_id = t.id AND tt.tag_id = $6::bigint))
  AND ($7::date IS NULL
       OR (t.date, t.id) < ($7::date, $8::bigint))
ORDER BY t.date DESC, t.id DESC
LIMIT $9
`

type ListTransactionsParams struct {
	BookID     int64
	FromDate   *time.Time
	ToDate     *time.Time
	AccountIds []int64
	Q          *string
	TagID      *int64
	CursorDate *time.Time
	CursorID   *int64
	Lim        int32
}

// Newest first, keyset-paginated on (date, id). account_ids is the selected
// account plus its descendants, computed in Go; empty means no filter.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.BookID,
		arg.FromDate,
		arg.ToDate,
		arg.AccountIds,
		arg.Q,
		arg.TagID,
		arg.CursorDate,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Date,
			&i.Payee,
			&i.Memo,
			&i.Source,
			&i.ExternalID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxPostingPosition = `-- name: MaxPostingPosition :one
SELECT coalesce(max(position), 0)::INT FROM postings WHERE transaction_id = $1
`

func (q *Queries) MaxPostingPosition(ctx context.Context, transactionID int64) (int32, error) {
	row := q.db.QueryRow(ctx, maxPostingPosition, transactionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const rebasePostings = `-- name: RebasePostings :many
SELECT p.id, p.transaction_id, p.account_id, p.commodity, p.amount, p.base_amount, t.date
FROM postings p JOIN transactions t ON t.id = p.transaction_id
WHERE t.book_id = $1
ORDER BY t.id, p.position
`

type RebasePostingsRow struct {
	ID            int64
	TransactionID int64
	AccountID     int64
	Commodity     string
	Amount        decimal.Decimal
	BaseAmount    decimal.Decimal
	Date          time.Time
}

// Every posting of a book with its transaction date, for a change of base.
func (q *Queries) RebasePostings(ctx context.Context, bookID int64) ([]RebasePostingsRow, error) {
	rows, err := q.db.Query(ctx, rebasePostings, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RebasePostingsRow{}
	for rows.Next() {
		var i RebasePostingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Commodity,
			&i.Amount,
			&i.BaseAmount,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPostingBase = `-- name: SetPostingBase :exec
UPDATE postings SET base_amount = $1 WHERE id = $2
`

type SetPostingBaseParams struct {
	BaseAmount decimal.Decimal
	ID         int64
}

func (q *Queries) SetPostingBase(ctx context.Context, arg SetPostingBaseParams) error {
	_, err := q.db.Exec(ctx, setPostingBase, arg.BaseAmount, arg.ID)
	return err
}

const tagExpenses = `-- name: TagExpenses :many
SELECT p.account_id, coalesce(sum(p.base_amount), 0)::numeric AS base_amount
FROM tags tg
JOIN transaction_tags tt ON tt.tag_id = tg.id
JOIN postings p ON p.transaction_id = tt.transaction_id
JOIN accounts a ON a.id = p.account_id
WHERE tg.book_id = $1 AND lower(tg.name) = lower($2) AND a.class = 'expense'
GROUP BY p.account_id
`

type TagExpensesParams struct {
	BookID int64
	Name   string
}

type TagExpensesRow struct {
	AccountID  int64
	BaseAmount decimal.Decimal
}

// One tag's expense postings, per account.
func (q *Queries) TagExpenses(ctx context.Context, arg TagExpensesParams) ([]TagExpensesRow, error) {
	rows, err := q.db.Query(ctx, tagExpenses, arg.BookID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagExpensesRow{}
	for rows.Next() {
		var i TagExpensesRow
		if err := rows.Scan(&i.AccountID, &i.BaseAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagSummaries = `-- name: TagSummaries :many
SELECT tg.name,
       count(DISTINCT t.id)::BIGINT                                          AS transactions,
       min(t.date)::DATE                                                     AS first_date,
       max(t.date)::DATE                                                     AS last_date,
       coalesce(sum(p.base_amount) FILTER (WHERE a.class = 'expense'), 0)::numeric AS expenses
FROM tags tg
JOIN transaction_tags tt ON tt.tag_id = tg.id
JOIN transactions t ON t.id = tt.transaction_id
JOIN postings p ON p.transaction_id = t.id
JOIN accounts a ON a.id = p.account_id
WHERE tg.book_id = $1
GROUP BY tg.name
ORDER BY max(t.date) DESC, tg.name
`

type TagSummariesRow struct {
	Name         string
	Transactions int64
	FirstDate    time.Time
	LastDate     time.Time
	Expenses     decimal.Decimal
}

// Every tag of a book with its span and what its transactions spent
// (expense postings at their stored base amounts: miles at cost).
func (q *Queries) TagSummaries(ctx context.Context, bookID int64) ([]TagSummariesRow, error) {
	rows, err := q.db.Query(ctx, tagSummaries, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagSummariesRow{}
	for rows.Next() {
		var i TagSummariesRow
		if err := rows.Scan(
			&i.Name,
			&i.Transactions,
			&i.FirstDate,
			&i.LastDate,
			&i.Expenses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions SET date = $1, payee = $2, memo = $3, updated_by = $4
WHERE book_id = $5 AND id = $6
RETURNING id, book_id, date, payee, memo, source, external_id, created_by, updated_by, created_at, updated_at
`

type UpdateTransactionParams struct {
	Date   time.Time
	Payee  string
	Memo   string
	UserID *int64
	BookID int64
	ID     int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.Date,
		arg.Payee,
		arg.Memo,
		arg.UserID,
		arg.BookID,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Date,
		&i.Payee,
		&i.Memo,
		&i.Source,
		&i.ExternalID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (book_id, name) VALUES ($1, $2)
ON CONFLICT (book_id, lower(name)) DO UPDATE SET name = tags.name
RETURNING id, book_id, name
`

type UpsertTagParams struct {
	BookID int64
	Name   string
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.BookID, arg.Name)
	var i Tag
	err := row.Scan(&i.ID, &i.BookID, &i.Name)
	return i, err
}
