// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, display_name, language, display_currency, timezone, is_admin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, email, password_hash, display_name, is_admin, is_active, language, display_currency, timezone, date_format, theme, default_book_id, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Username        string
	Email           string
	PasswordHash    string
	DisplayName     string
	Language        string
	DisplayCurrency string
	Timezone        string
	IsAdmin         bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Language,
		arg.DisplayCurrency,
		arg.Timezone,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.Language,
		&i.DisplayCurrency,
		&i.Timezone,
		&i.DateFormat,
		&i.Theme,
		&i.DefaultBookID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, display_name, is_admin, is_active, language, display_currency, timezone, date_format, theme, default_book_id, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.Language,
		&i.DisplayCurrency,
		&i.Timezone,
		&i.DateFormat,
		&i.Theme,
		&i.DefaultBookID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, display_name, is_admin, is_active, language, display_currency, timezone, date_format, theme, default_book_id, last_login_at, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.Language,
		&i.DisplayCurrency,
		&i.Timezone,
		&i.DateFormat,
		&i.Theme,
		&i.DefaultBookID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setDefaultBookIfUnset = `-- name: SetDefaultBookIfUnset :exec
UPDATE users SET default_book_id = $2 WHERE id = $1 AND default_book_id IS NULL
`

type SetDefaultBookIfUnsetParams struct {
	ID            int64
	DefaultBookID *int64
}

func (q *Queries) SetDefaultBookIfUnset(ctx context.Context, arg SetDefaultBookIfUnsetParams) error {
	_, err := q.db.Exec(ctx, setDefaultBookIfUnset, arg.ID, arg.DefaultBookID)
	return err
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users SET is_admin = $2 WHERE id = $1
`

type SetUserAdminParams struct {
	ID      int64
	IsAdmin bool
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.Exec(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateUserIdentity = `-- name: UpdateUserIdentity :one
UPDATE users SET username = $1, email = $2 WHERE id = $3
RETURNING id, username, email, password_hash, display_name, is_admin, is_active, language, display_currency, timezone, date_format, theme, default_book_id, last_login_at, created_at, updated_at
`

type UpdateUserIdentityParams struct {
	Username string
	Email    string
	ID       int64
}

func (q *Queries) UpdateUserIdentity(ctx context.Context, arg UpdateUserIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserIdentity, arg.Username, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.Language,
		&i.DisplayCurrency,
		&i.Timezone,
		&i.DateFormat,
		&i.Theme,
		&i.DefaultBookID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users SET
    display_name     = $1,
    language         = $2,
    display_currency = $3,
    timezone         = $4,
    date_format      = $5,
    theme            = $6,
    default_book_id  = $7
WHERE id = $8
RETURNING id, username, email, password_hash, display_name, is_admin, is_active, language, display_currency, timezone, date_format, theme, default_book_id, last_login_at, created_at, updated_at
`

type UpdateUserSettingsParams struct {
	DisplayName     string
	Language        string
	DisplayCurrency string
	Timezone        string
	DateFormat      string
	Theme           string
	DefaultBookID   *int64
	ID              int64
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.DisplayName,
		arg.Language,
		arg.DisplayCurrency,
		arg.Timezone,
		arg.DateFormat,
		arg.Theme,
		arg.DefaultBookID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsAdmin,
		&i.IsActive,
		&i.Language,
		&i.DisplayCurrency,
		&i.Timezone,
		&i.DateFormat,
		&i.Theme,
		&i.DefaultBookID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
